---
sidebar: sidebar 
permalink: trident-docker/deploy-docker.html 
keywords: deploy, Trident, trident for docker, docker 
summary: Trident for Docker bietet eine direkte Integration mit dem Docker-Ökosystem für NetApp Speicherplattformen.  Es unterstützt die Bereitstellung und Verwaltung von Speicherressourcen von der Speicherplattform bis hin zu Docker-Hosts und bietet ein Framework für die zukünftige Integration weiterer Plattformen. 
---
= Trident einsetzen
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Trident for Docker bietet eine direkte Integration mit dem Docker-Ökosystem für NetApp Speicherplattformen.  Es unterstützt die Bereitstellung und Verwaltung von Speicherressourcen von der Speicherplattform bis hin zu Docker-Hosts und bietet ein Framework für die zukünftige Integration weiterer Plattformen.

Mehrere Instanzen von Trident können gleichzeitig auf demselben Host ausgeführt werden.  Dies ermöglicht die gleichzeitige Anbindung an mehrere Speichersysteme und Speichertypen sowie die Möglichkeit, den für die Docker-Volumes verwendeten Speicher individuell anzupassen.

.Was du brauchst
Siehe dielink:prereqs-docker.html["Voraussetzungen für die Bereitstellung"] . Sobald Sie sichergestellt haben, dass die Voraussetzungen erfüllt sind, können Sie Trident einsetzen.



== Docker-verwaltete Plugin-Methode (Version 1.13/17.03 und höher)

.Bevor Sie beginnen

NOTE: Wenn Sie Trident vor Docker 1.13/17.03 in der traditionellen Daemon-Methode verwendet haben, stellen Sie sicher, dass Sie den Trident -Prozess stoppen und Ihren Docker-Daemon neu starten, bevor Sie die Methode mit dem verwalteten Plugin verwenden.

. Alle laufenden Instanzen stoppen:
+
[source, console]
----
pkill /usr/local/bin/netappdvp
pkill /usr/local/bin/trident
----
. Docker neu starten.
+
[source, console]
----
systemctl restart docker
----
. Stellen Sie sicher, dass Sie Docker Engine 17.03 (neu 1.13) oder höher installiert haben.
+
[source, console]
----
docker --version
----
+
Wenn Ihre Version veraltet ist, https://docs.docker.com/engine/install/["Installieren oder aktualisieren Sie Ihre Installation"^] .



.Schritte
. Erstellen Sie eine Konfigurationsdatei und geben Sie die Optionen wie folgt an:
+
**  `config`Der Standarddateiname ist `config.json` Sie können jedoch einen beliebigen Namen verwenden, indem Sie ihn angeben. `config` Option mit dem Dateinamen.  Die Konfigurationsdatei muss sich im folgenden Verzeichnis befinden: `/etc/netappdvp` Verzeichnis auf dem Hostsystem.
** `log-level`: Protokollierungsstufe festlegen(`debug` , `info` , `warn` , `error` , `fatal` ).  Standardmäßig ist `info` .
** `debug`: Geben Sie an, ob die Debug-Protokollierung aktiviert ist.  Standardwert ist „false“.  Überschreibt den Protokollierungsgrad, falls wahr.
+
... Erstellen Sie einen Speicherort für die Konfigurationsdatei:
+
[source, console]
----
sudo mkdir -p /etc/netappdvp
----
... Erstellen Sie die Konfigurationsdatei:
+
[source, console]
----
cat << EOF > /etc/netappdvp/config.json
----
+
[source, json]
----
{
  "version": 1,
  "storageDriverName": "ontap-nas",
  "managementLIF": "10.0.0.1",
  "dataLIF": "10.0.0.2",
  "svm": "svm_nfs",
  "username": "vsadmin",
  "password": "password",
  "aggregate": "aggr1"
}
EOF
----




. Starten Sie Trident mithilfe des verwalteten Plugin-Systems.  Ersetzen `<version>` mit der von Ihnen verwendeten Plugin-Version (xxx.xx.x).
+
[source, console]
----
docker plugin install --grant-all-permissions --alias netapp netapp/trident-plugin:<version> config=myConfigFile.json
----
. Beginnen Sie mit der Nutzung von Trident, um Speicherplatz des konfigurierten Systems zu belegen.
+
.. Erstellen Sie ein Volume mit dem Namen „firstVolume“:
+
[source, console]
----
docker volume create -d netapp --name firstVolume
----
.. Erstellen Sie ein Standardvolume beim Start des Containers:
+
[source, console]
----
docker run --rm -it --volume-driver netapp --volume secondVolume:/my_vol alpine ash
----
.. Entfernen Sie die Lautstärke "firstVolume":
+
[source, console]
----
docker volume rm firstVolume
----






== Traditionelle Methode (Version 1.12 oder früher)

.Bevor Sie beginnen
. Stellen Sie sicher, dass Sie Docker Version 1.10 oder höher verwenden.
+
[source, console]
----
docker --version
----
+
Sollte Ihre Version veraltet sein, aktualisieren Sie Ihre Installation.

+
[source, console]
----
curl -fsSL https://get.docker.com/ | sh
----
+
Oder, https://docs.docker.com/engine/install/["Befolgen Sie die Anweisungen für Ihre Verteilung."^] .

. Stellen Sie sicher, dass NFS und/oder iSCSI für Ihr System konfiguriert ist.


.Schritte
. Installieren und konfigurieren Sie das NetApp Docker Volume Plugin:
+
.. Laden Sie die Anwendung herunter und entpacken Sie sie:
+
[source, console]
----
wget https://github.com/NetApp/trident/releases/download/v25.06.0/trident-installer-25.06.0.tar.gz
tar zxf trident-installer-25.06.0.tar.gz
----
.. An eine Position im Papierkorbpfad verschieben:
+
[source, console]
----
sudo mv trident-installer/extras/bin/trident /usr/local/bin/
sudo chown root:root /usr/local/bin/trident
sudo chmod 755 /usr/local/bin/trident
----
.. Erstellen Sie einen Speicherort für die Konfigurationsdatei:
+
[source, console]
----
sudo mkdir -p /etc/netappdvp
----
.. Erstellen Sie die Konfigurationsdatei:
+
[source, console]
----
cat << EOF > /etc/netappdvp/ontap-nas.json
----
+
[source, json]
----
{
  "version": 1,
  "storageDriverName": "ontap-nas",
  "managementLIF": "10.0.0.1",
  "dataLIF": "10.0.0.2",
  "svm": "svm_nfs",
  "username": "vsadmin",
  "password": "password",
  "aggregate": "aggr1"
}
EOF
----


. Nachdem Sie die Binärdatei platziert und die Konfigurationsdatei erstellt haben, starten Sie den Trident Daemon mit der gewünschten Konfigurationsdatei.
+
[source, console]
----
sudo trident --config=/etc/netappdvp/ontap-nas.json
----
+

NOTE: Sofern nicht anders angegeben, lautet der Standardname für den Volume-Treiber "netapp".

+
Nach dem Start des Daemons können Sie Volumes mithilfe der Docker CLI-Schnittstelle erstellen und verwalten.

. Ein Volume erstellen:
+
[source, console]
----
docker volume create -d netapp --name trident_1
----
. Beim Starten eines Containers ein Docker-Volume bereitstellen:
+
[source, console]
----
docker run --rm -it --volume-driver netapp --volume trident_2:/my_vol alpine ash
----
. Entfernen eines Docker-Volumes:
+
[source, console]
----
docker volume rm trident_1
----
+
[source, console]
----
docker volume rm trident_2
----




== Trident beim Systemstart starten

Eine Beispiel-Unit-Datei für systemd-basierte Systeme finden Sie unter `contrib/trident.service.example` im Git-Repository.  Um die Datei mit RHEL zu verwenden, gehen Sie wie folgt vor:

. Kopieren Sie die Datei an den richtigen Speicherort.
+
Sie sollten eindeutige Namen für die Unit-Dateien verwenden, wenn Sie mehr als eine Instanz ausführen.

+
[source, console]
----
cp contrib/trident.service.example /usr/lib/systemd/system/trident.service
----
. Bearbeiten Sie die Datei, ändern Sie die Beschreibung (Zeile 2) so, dass sie dem Treibernamen entspricht, und den Pfad zur Konfigurationsdatei (Zeile 9) so, dass er Ihre Umgebung widerspiegelt.
. Systemd muss neu geladen werden, damit die Änderungen übernommen werden:
+
[source, console]
----
systemctl daemon-reload
----
. Aktivieren Sie den Dienst.
+
Dieser Name variiert je nachdem, wie Sie die Datei im `/usr/lib/systemd/system` Verzeichnis.

+
[source, console]
----
systemctl enable trident
----
. Starten Sie den Dienst.
+
[source, console]
----
systemctl start trident
----
. Status ansehen.
+
[source, console]
----
systemctl status trident
----



NOTE: Jedes Mal, wenn Sie die Unit-Datei ändern, führen Sie den Befehl aus. `systemctl daemon-reload` Befehl, damit es die Änderungen erkennt.
