---
sidebar: sidebar 
permalink: trident-docker/known-issues-docker.html 
keywords: known issues, trident, trident for docker, docker 
summary: Hier finden Sie Informationen zu bekannten Problemen bei der Verwendung von Trident mit Docker. 
---
= Bekannte Probleme und Einschränkungen
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Hier finden Sie Informationen zu bekannten Problemen und Einschränkungen bei der Verwendung von Trident mit Docker.



== Beim Upgrade des Trident Docker Volume Plugins von älteren Versionen auf Version 20.10 oder höher tritt ein Upgrade-Fehler mit der Fehlermeldung „Datei oder Verzeichnis nicht gefunden“ auf.

.Problemumgehung
. Deaktivieren Sie das Plugin.
+
[source, console]
----
docker plugin disable -f netapp:latest
----
. Entfernen Sie das Plugin.
+
[source, console]
----
docker plugin rm -f netapp:latest
----
. Installieren Sie das Plugin erneut, indem Sie die zusätzlichen Informationen bereitstellen. `config` Parameter.
+
[source, console]
----
docker plugin install netapp/trident-plugin:20.10 --alias netapp --grant-all-permissions config=config.json
----




== Die Bandnamen müssen mindestens 2 Zeichen lang sein.


NOTE: Dies ist eine Einschränkung des Docker-Clients.  Der Client interpretiert einen einstelligen Namen als Windows-Pfad. https://github.com/moby/moby/issues/25773["Siehe Fehler 25773"^] .



== Docker Swarm weist bestimmte Verhaltensweisen auf, die Trident daran hindern, es mit jeder Speicher- und Treiberkombination zu unterstützen.

* Docker Swarm verwendet derzeit den Volumennamen anstelle der Volumen-ID als eindeutigen Volumenbezeichner.
* Volumenanforderungen werden gleichzeitig an jeden Knoten in einem Swarm-Cluster gesendet.
* Volume-Plugins (einschließlich Trident) müssen auf jedem Knoten in einem Swarm-Cluster unabhängig ausgeführt werden.  Aufgrund der Funktionsweise von ONTAP und der Art und Weise, wie die `ontap-nas` Und `ontap-san` Wenn Fahrer funktionieren, sind sie die einzigen, die innerhalb dieser Grenzen arbeiten können.


Die übrigen Treiber sind Problemen wie Race Conditions ausgesetzt, die dazu führen können, dass für eine einzelne Anfrage eine große Anzahl von Volumes erstellt wird, ohne dass es einen klaren "Gewinner" gibt; beispielsweise verfügt Element über eine Funktion, die es ermöglicht, dass Volumes den gleichen Namen, aber unterschiedliche IDs haben.

NetApp hat dem Docker-Team Feedback gegeben, es gibt aber keine Hinweise auf weitere Maßnahmen.



== Wird eine FlexGroup bereitgestellt, stellt ONTAP keine zweite FlexGroup bereit, wenn die zweite FlexGroup ein oder mehrere Aggregate mit der bereitzustellenden FlexGroup gemeinsam hat.
