---
sidebar: sidebar 
permalink: trident-docker/multiple-instances-docker.html 
keywords: deploy, Trident, docker, trident for docker, managed plugin, trident instances, alias 
summary: Mehrere Instanzen von Trident sind erforderlich, wenn Sie mehrere Speicherkonfigurationen gleichzeitig nutzen möchten.  Der Schlüssel zur Erzeugung mehrerer Instanzen liegt darin, ihnen mithilfe der Option --alias beim containerisierten Plugin oder der Option --volume-driver bei der Instanziierung von Trident auf dem Host unterschiedliche Namen zu geben. 
---
= Mehrere Trident Instanzen verwalten
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mehrere Instanzen von Trident sind erforderlich, wenn Sie mehrere Speicherkonfigurationen gleichzeitig nutzen möchten.  Der Schlüssel zu mehreren Instanzen besteht darin, ihnen mithilfe des `--alias` Option mit dem containerisierten Plugin, oder `--volume-driver` Option beim Instanziieren von Trident auf dem Host.



== Schritte für das Docker-verwaltete Plugin (Version 1.13/17.03 oder höher)

. Starten Sie die erste Instanz unter Angabe eines Alias und einer Konfigurationsdatei.
+
[source, console]
----
docker plugin install --grant-all-permissions --alias silver netapp/trident-plugin:21.07 config=silver.json
----
. Starten Sie die zweite Instanz und geben Sie dabei einen anderen Alias und eine andere Konfigurationsdatei an.
+
[source, console]
----
docker plugin install --grant-all-permissions --alias gold netapp/trident-plugin:21.07 config=gold.json
----
. Erstellen Sie Volumes, indem Sie den Alias als Treibernamen angeben.
+
Zum Beispiel für das Goldvolumen:

+
[source, console]
----
docker volume create -d gold --name ntapGold
----
+
Beispiel: Silbervolumen

+
[source, console]
----
docker volume create -d silver --name ntapSilver
----




== Schritte für die traditionelle Version (Version 1.12 oder älter)

. Starten Sie das Plugin mit einer NFS-Konfiguration unter Verwendung einer benutzerdefinierten Treiber-ID:
+
[source, console]
----
sudo trident --volume-driver=netapp-nas --config=/path/to/config-nfs.json
----
. Starten Sie das Plugin mit einer iSCSI-Konfiguration unter Verwendung einer benutzerdefinierten Treiber-ID:
+
[source, console]
----
sudo trident --volume-driver=netapp-san --config=/path/to/config-iscsi.json
----
. Docker-Volumes für jede Treiberinstanz bereitstellen:
+
Zum Beispiel für NFS:

+
[source, console]
----
docker volume create -d netapp-nas --name my_nfs_vol
----
+
Zum Beispiel für iSCSI:

+
[source, console]
----
docker volume create -d netapp-san --name my_iscsi_vol
----

