---
sidebar: sidebar 
permalink: trident-docker/stor-config.html 
keywords: deploy, trident, docker, trident for docker, nfs, iscsi, protocol, nfs protocol, iscsi protocol, configure host, host config, storage config, options, variables, ontap, element, storage pool, cvs, cvs-performance, service type, service level, cloud volumes service, cloud volumes 
summary: Sehen Sie sich die für Ihre Trident -Konfigurationen verfügbaren Konfigurationsoptionen an. 
---
= Speicherkonfigurationsoptionen
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sehen Sie sich die für Ihre Trident -Konfigurationen verfügbaren Konfigurationsoptionen an.



== Globale Konfigurationsoptionen

Diese Konfigurationsoptionen gelten für alle Trident -Konfigurationen, unabhängig von der verwendeten Speicherplattform.

[cols="3*"]
|===
| Option | Beschreibung | Beispiel 


| `version`  a| 
Versionsnummer der Konfigurationsdatei
 a| 
`1`



| `storageDriverName`  a| 
Name des Speichertreibers
 a| 
`ontap-nas`, `ontap-san` , `ontap-nas-economy` ,
`ontap-nas-flexgroup` , `solidfire-san`



| `storagePrefix`  a| 
Optionales Präfix für Datenträgernamen.  Standard: `netappdvp_` .
 a| 
`staging_`



| `limitVolumeSize`  a| 
Optionale Beschränkung der Volumengrößen.  Standardwert: "" (nicht erzwungen)
 a| 
`10g`

|===

TIP: Nicht verwenden `storagePrefix` (einschließlich des Standard-Backends) für Element-Backends.  Standardmäßig ist die `solidfire-san` Der Treiber wird diese Einstellung ignorieren und kein Präfix verwenden.  NetApp empfiehlt, entweder eine spezifische Mandanten-ID für das Docker-Volume-Mapping zu verwenden oder die Attributdaten zu nutzen, die mit der Docker-Version, Treiberinformationen und dem Rohnamen von Docker gefüllt sind, falls eine Namensmanipulation vorgenommen wurde.

Es stehen Standardoptionen zur Verfügung, sodass Sie diese nicht bei jedem neu erstellten Volume angeben müssen.  Der `size` Diese Option ist für alle Controllertypen verfügbar.  Ein Beispiel für die Festlegung der Standard-Volumegröße finden Sie im Abschnitt ONTAP -Konfiguration.

[cols="3*"]
|===
| Option | Beschreibung | Beispiel 


| `size`  a| 
Optionale Standardgröße für neue Volumes.  Standard: `1G`
 a| 
`10G`

|===


== ONTAP-Konfiguration

Zusätzlich zu den oben genannten globalen Konfigurationswerten stehen bei Verwendung von ONTAP die folgenden Optionen auf oberster Ebene zur Verfügung.

[cols="3*"]
|===
| Option | Beschreibung | Beispiel 


| `managementLIF`  a| 
IP-Adresse des ONTAP -Management-LIF.  Sie können einen vollqualifizierten Domänennamen (FQDN) angeben.
 a| 
`10.0.0.1`



| `dataLIF`  a| 
IP-Adresse des Protokolls LIF.

* ONTAP NAS-Treiber *: NetApp empfiehlt die Angabe `dataLIF` .  Falls keine Daten angegeben werden, ruft Trident die dataLIFs vom SVM ab.  Sie können einen vollqualifizierten Domänennamen (FQDN) angeben, der für die NFS-Mount-Operationen verwendet werden soll. Dadurch können Sie ein Round-Robin-DNS erstellen, um die Last auf mehrere DataLIFs zu verteilen.

* ONTAP SAN-Treiber*: Nicht für iSCSI oder FC angeben.  Trident Anwendungenlink:https://docs.netapp.com/us-en/ontap/san-admin/selective-lun-map-concept.html["ONTAP Selective LUN Map"^] um die iSCSI- oder FC-LIFs zu ermitteln, die zum Aufbau einer Multipath-Sitzung benötigt werden.  Es wird eine Warnung generiert, wenn `dataLIF` ist explizit definiert.
 a| 
`10.0.0.2`



| `svm`  a| 
Zu verwendende virtuelle Speichermaschine (erforderlich, wenn es sich bei der Management-LIF um eine Cluster-LIF handelt)
 a| 
`svm_nfs`



| `username`  a| 
Benutzername für die Verbindung zum Speichergerät
 a| 
`vsadmin`



| `password`  a| 
Passwort zum Verbinden mit dem Speichergerät
 a| 
`secret`



| `aggregate`  a| 
Aggregat für die Bereitstellung (optional; falls festgelegt, muss es der SVM zugewiesen werden).  Für die `ontap-nas-flexgroup` Treiber, diese Option wird ignoriert.  Alle dem SVM zugewiesenen Aggregate werden zur Bereitstellung eines FlexGroup Volumes verwendet.
 a| 
`aggr1`



| `limitAggregateUsage`  a| 
Optional: Die Bereitstellung schlägt fehl, wenn die Nutzung diesen Prozentsatz überschreitet.
 a| 
`75%`



| `nfsMountOptions`  a| 
Feingranulare Steuerung der NFS-Mount-Optionen; Standardwert ist "-o nfsvers=3".  *Nur verfügbar für die `ontap-nas` Und `ontap-nas-economy` Fahrer*. https://www.netapp.com/pdf.html?item=/media/10720-tr-4067.pdf["Informationen zur NFS-Hostkonfiguration finden Sie hier."^] .
 a| 
`-o nfsvers=4`



| `igroupName`  a| 
Trident erstellt und verwaltet pro Knoten `igroups` als `netappdvp` .

Dieser Wert darf weder geändert noch weggelassen werden.

*Nur verfügbar für die `ontap-san` Treiber*.
 a| 
`netappdvp`



| `limitVolumeSize`  a| 
Maximal anforderbares Volumen.
 a| 
`300g`



| `qtreesPerFlexvol`  a| 
Die maximale Anzahl an Qtrees pro FlexVol muss im Bereich [50, 300] liegen; der Standardwert ist 200.

*Für die `ontap-nas-economy` Mit dieser Option kann die maximale Anzahl von Qtrees pro FlexVol* angepasst werden.
 a| 
`300`



 a| 
`sanType`
| *Unterstützt für `ontap-san` Nur für den Fahrer.*  Zur Auswahl verwenden `iscsi` für iSCSI, `nvme` für NVMe/TCP oder `fcp` für SCSI über Fibre Channel (FC). | `iscsi`falls leer 


| `limitVolumePoolSize` | *Unterstützt für `ontap-san-economy` Und `ontap-san-economy` Nur für Fahrer.*  Begrenzt die FlexVol -Größen in den ONTAP Treibern ontap-nas-economy und ontap-SAN-economy.  a| 
`300g`

|===
Es stehen Standardoptionen zur Verfügung, sodass Sie diese nicht bei jedem erstellten Volume angeben müssen:

[cols="1,3,2"]
|===
| Option | Beschreibung | Beispiel 


| `spaceReserve`  a| 
Platzreservierungsmodus; `none` (Thin Provisioning) oder `volume` (dick)
 a| 
`none`



| `snapshotPolicy`  a| 
Zu verwendende Snapshot-Richtlinie, Standardwert ist `none`
 a| 
`none`



| `snapshotReserve`  a| 
Snapshot-Reserveprozentsatz, Standardwert ist "", um den ONTAP Standardwert zu akzeptieren
 a| 
`10`



| `splitOnClone`  a| 
Beim Erstellen eines Klons diesen vom übergeordneten Klon trennen (Standardeinstellung). `false`
 a| 
`false`



| `encryption`  a| 
Aktiviert die NetApp Volume-Verschlüsselung (NVE) auf dem neuen Volume; Standardwert: `false` .  Um diese Option nutzen zu können, muss NVE auf dem Cluster lizenziert und aktiviert sein.

Wenn NAE im Backend aktiviert ist, wird jedes in Trident bereitgestellte Volume NAE-fähig sein.

Weitere Informationen finden Sie unter:link:../trident-reco/security-reco.html["Wie Trident mit NVE und NAE zusammenarbeitet"] .
 a| 
true



| `unixPermissions`  a| 
NAS-Option für bereitgestellte NFS-Volumes, Standardwert `777`
 a| 
`777`



| `snapshotDir`  a| 
NAS-Option für den Zugriff auf die `.snapshot` Verzeichnis.
 a| 
"true" für NFSv4, "false" für NFSv3



| `exportPolicy`  a| 
NAS-Option für die zu verwendende NFS-Exportrichtlinie, Standardwert `default`
 a| 
`default`



| `securityStyle`  a| 
NAS-Option für den Zugriff auf das bereitgestellte NFS-Volume.

NFS unterstützt `mixed` Und `unix` Sicherheitsstile.  Standardmäßig ist `unix` .
 a| 
`unix`



| `fileSystemType`  a| 
SAN-Option zur Auswahl des Dateisystemtyps, Standardwert: `ext4`
 a| 
`xfs`



| `tieringPolicy`  a| 
Zu verwendende Tiering-Richtlinie, Standardwert ist `none` .
 a| 
`none`

|===


=== Skalierungsoptionen

Der `ontap-nas` Und `ontap-san` Die Treiber erstellen für jedes Docker-Volume ein ONTAP FlexVol .  ONTAP unterstützt bis zu 1000 FlexVols pro Clusterknoten, wobei der Cluster maximal 12.000 FlexVol -Volumes umfassen kann. Wenn Ihre Docker-Volume-Anforderungen innerhalb dieser Beschränkung liegen, `ontap-nas` Der Treiber ist aufgrund der zusätzlichen Funktionen von FlexVols, wie Docker-Volume-granularen Snapshots und Klonen, die bevorzugte NAS-Lösung.

Wenn Sie mehr Docker-Volumes benötigen, als die FlexVol Grenzwerte zulassen, wählen Sie die Option `ontap-nas-economy` oder die `ontap-san-economy` Treiber.

Der `ontap-nas-economy` Der Treiber erstellt Docker-Volumes als ONTAP Qtrees innerhalb eines Pools von automatisch verwalteten FlexVol Volumes.  Qtrees bieten eine weitaus größere Skalierbarkeit, bis zu 100.000 pro Clusterknoten und 2.400.000 pro Cluster, allerdings auf Kosten einiger Funktionen.  Der `ontap-nas-economy` Der Treiber unterstützt weder Docker-Volume-granulare Snapshots noch das Klonen.


NOTE: Der `ontap-nas-economy` Der Treiber wird derzeit in Docker Swarm nicht unterstützt, da Docker Swarm die Volume-Erstellung nicht über mehrere Knoten hinweg orchestriert.

Der `ontap-san-economy` Der Treiber erstellt Docker-Volumes als ONTAP -LUNs innerhalb eines gemeinsam genutzten Pools von automatisch verwalteten FlexVol Volumes.  Auf diese Weise ist jedes FlexVol nicht auf nur eine LUN beschränkt und bietet eine bessere Skalierbarkeit für SAN-Workloads.  Abhängig vom Speicherarray unterstützt ONTAP bis zu 16384 LUNs pro Cluster.  Da es sich bei den Volumes im Kern um LUNs handelt, unterstützt dieser Treiber Docker-volume-granulare Snapshots und Klonen.

Wählen Sie das Symbol `ontap-nas-flexgroup` Treiber zur Steigerung der Parallelität auf ein einzelnes Volume, das mit Milliarden von Dateien in den Petabyte-Bereich anwachsen kann.  Zu den idealen Anwendungsfällen für FlexGroups gehören KI/ML/DL, Big Data und Analytik, Softwareentwicklung, Streaming, Dateispeicher und so weiter.  Trident verwendet alle einem SVM zugewiesenen Aggregate bei der Bereitstellung eines FlexGroup -Volumes.  Die FlexGroup Unterstützung in Trident erfordert außerdem folgende Überlegungen:

* Erfordert ONTAP Version 9.2 oder höher.
* Zum jetzigen Zeitpunkt unterstützen FlexGroups nur NFS v3.
* Es wird empfohlen, die 64-Bit-NFSv3-Kennungen für die SVM zu aktivieren.
* Die empfohlene Mindestgröße für FlexGroup Mitglieder/Volumes beträgt 100 GiB.
* Das Klonen von FlexGroup -Volumes wird nicht unterstützt.


Weitere Informationen zu FlexGroups und für FlexGroups geeigneten Workloads finden Sie in der https://www.netapp.com/pdf.html?item=/media/12385-tr4571pdf.pdf["NetApp FlexGroup Volume: Best Practices und Implementierungsleitfaden"^] .

Um erweiterte Funktionen und große Skalierbarkeit in derselben Umgebung zu nutzen, können Sie mehrere Instanzen des Docker Volume Plugins ausführen, wobei eine davon verwendet wird. `ontap-nas` und ein weiterer, der `ontap-nas-economy` .



=== Benutzerdefinierte ONTAP Rolle für Trident

Sie können eine ONTAP Clusterrolle mit minimalen Berechtigungen erstellen, sodass Sie für Operationen in Trident nicht die ONTAP Administratorrolle verwenden müssen.  Wenn Sie den Benutzernamen in einer Trident Backend-Konfiguration angeben, verwendet Trident die von Ihnen erstellte ONTAP Clusterrolle, um die Operationen durchzuführen.

Siehelink:https://github.com/NetApp/trident/tree/master/contrib/ontap/trident_role["Trident -Benutzerrollengenerator"] Weitere Informationen zum Erstellen benutzerdefinierter Trident -Rollen finden Sie hier.

[role="tabbed-block"]
====
.Verwendung der ONTAP Befehlszeile
--
. Erstellen Sie eine neue Rolle mit folgendem Befehl:
+
`security login role create <role_name\> -cmddirname "command" -access all -vserver <svm_name\>`

. Erstellen Sie einen Benutzernamen für den Trident -Benutzer:
+
`security login create -username <user_name\> -application ontapi -authmethod password -role <name_of_role_in_step_1\> -vserver <svm_name\> -comment "user_description"`
`security login create -username <user_name\> -application http -authmethod password -role <name_of_role_in_step_1\> -vserver <svm_name\> -comment "user_description"`

. Ordnen Sie die Rolle dem Benutzer zu:
+
`security login modify username <user_name\> -vserver <svm_name\> -role <role_name\> -application ontapi -application console -authmethod <password\>`



--
.Systemmanager verwenden
--
Führen Sie die folgenden Schritte im ONTAP System Manager aus:

. *Erstellen Sie eine benutzerdefinierte Rolle*:
+
.. Um eine benutzerdefinierte Rolle auf Clusterebene zu erstellen, wählen Sie *Cluster > Einstellungen*.
+
(Oder) Um eine benutzerdefinierte Rolle auf SVM-Ebene zu erstellen, wählen Sie *Speicher > Speicher-VMs > `required SVM` > Einstellungen > Benutzer und Rollen*.

.. Wählen Sie das Pfeilsymbol (*->*) neben *Benutzer und Rollen* aus.
.. Wählen Sie unter *Rollen* die Option *+Hinzufügen*.
.. Definieren Sie die Regeln für die Rolle und klicken Sie auf *Speichern*.


. *Rolle dem Trident -Benutzer zuordnen*: + Führen Sie die folgenden Schritte auf der Seite *Benutzer und Rollen* aus:
+
.. Wählen Sie unter *Benutzer* das Symbol *+* zum Hinzufügen aus.
.. Wählen Sie den gewünschten Benutzernamen und anschließend eine Rolle im Dropdown-Menü für *Rolle* aus.
.. Klicken Sie auf *Speichern*.




--
====
Weitere Informationen finden Sie auf den folgenden Seiten:

* link:https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/FAQ__Custom_roles_for_administration_of_ONTAP["Benutzerdefinierte Rollen für die Administration von ONTAP"^]oderlink:https://docs.netapp.com/us-en/ontap/authentication/define-custom-roles-task.html["Benutzerdefinierte Rollen definieren"^]
* link:https://docs.netapp.com/us-en/ontap-automation/rest/rbac_roles_users.html#rest-api["Mit Rollen und Benutzern arbeiten"^]




=== Beispielhafte ONTAP Konfigurationsdateien

.NFS-Beispiel für den <code>ontap-nas</code>-Treiber
[%collapsible]
====
[source, json]
----
{
  "version": 1,
  "storageDriverName": "ontap-nas",
  "managementLIF": "10.0.0.1",
  "dataLIF": "10.0.0.2",
  "svm": "svm_nfs",
  "username": "vsadmin",
  "password": "password",
  "aggregate": "aggr1",
  "defaults": {
    "size": "10G",
    "spaceReserve": "none",
    "exportPolicy": "default"
  }
}
----
====
.NFS-Beispiel für den <code>ontap-nas-flexgroup</code>-Treiber
[%collapsible]
====
[source, json]
----
{
  "version": 1,
  "storageDriverName": "ontap-nas-flexgroup",
  "managementLIF": "10.0.0.1",
  "dataLIF": "10.0.0.2",
  "svm": "svm_nfs",
  "username": "vsadmin",
  "password": "password",
  "defaults": {
    "size": "100G",
    "spaceReserve": "none",
    "exportPolicy": "default"
  }
}
----
====
.NFS-Beispiel für den <code>ontap-nas-economy</code>-Treiber
[%collapsible]
====
[source, json]
----
{
  "version": 1,
  "storageDriverName": "ontap-nas-economy",
  "managementLIF": "10.0.0.1",
  "dataLIF": "10.0.0.2",
  "svm": "svm_nfs",
  "username": "vsadmin",
  "password": "password",
  "aggregate": "aggr1"
}
----
====
.iSCSI-Beispiel für den <code>ontap-san</code>-Treiber
[%collapsible]
====
[source, json]
----
{
  "version": 1,
  "storageDriverName": "ontap-san",
  "managementLIF": "10.0.0.1",
  "dataLIF": "10.0.0.3",
  "svm": "svm_iscsi",
  "username": "vsadmin",
  "password": "password",
  "aggregate": "aggr1",
  "igroupName": "netappdvp"
}
----
====
.NFS-Beispiel für den <code>ontap-san-economy</code>-Treiber
[%collapsible]
====
[source, json]
----
{
  "version": 1,
  "storageDriverName": "ontap-san-economy",
  "managementLIF": "10.0.0.1",
  "dataLIF": "10.0.0.3",
  "svm": "svm_iscsi_eco",
  "username": "vsadmin",
  "password": "password",
  "aggregate": "aggr1",
  "igroupName": "netappdvp"
}
----
====
.NVMe/TCP-Beispiel für den <code>ontap-san</code>-Treiber
[%collapsible]
====
[source, json]
----
{
  "version": 1,
  "backendName": "NVMeBackend",
  "storageDriverName": "ontap-san",
  "managementLIF": "10.0.0.1",
  "svm": "svm_nvme",
  "username": "vsadmin",
  "password": "password",
  "sanType": "nvme",
  "useREST": true
}
----
====
.SCSI über FC-Beispiel für den <code>ontap-san</code>-Treiber
[%collapsible]
====
[source, json]
----
{
  "version": 1,
  "backendName": "ontap-san-backend",
  "storageDriverName": "ontap-san",
  "managementLIF": "10.0.0.1",
  "sanType": "fcp",
  "svm": "trident_svm",
  "username": "vsadmin",
  "password": "password",
  "useREST": true
}
----
====


== Element-Softwarekonfiguration

Zusätzlich zu den globalen Konfigurationswerten stehen bei Verwendung der Element-Software (NetApp HCI/ SolidFire) folgende Optionen zur Verfügung.

[cols="3*"]
|===
| Option | Beschreibung | Beispiel 


| `Endpoint`  a| 
https://<login>:<password>@<mvip>/json-rpc/<element-version>
 a| 
https://admin:admin@192.168.160.3/json-rpc/8.0



| `SVIP`  a| 
iSCSI-IP-Adresse und Port
 a| 
10.0.0.7:3260



| `TenantName`  a| 
SolidFireF-Mandant (wird erstellt, falls nicht gefunden)
 a| 
`docker`



| `InitiatorIFace`  a| 
Schnittstelle angeben, wenn der iSCSI-Datenverkehr auf eine nicht standardmäßige Schnittstelle beschränkt wird
 a| 
`default`



| `Types`  a| 
QoS-Spezifikationen
 a| 
Siehe Beispiel unten



| `LegacyNamePrefix`  a| 
Präfix für aktualisierte Trident Installationen.  Wenn Sie eine Version von Trident vor 1.3.2 verwendet haben und ein Upgrade mit bestehenden Volumes durchführen, müssen Sie diesen Wert festlegen, um auf Ihre alten Volumes zugreifen zu können, die über die Volume-Name-Methode zugeordnet wurden.
 a| 
`netappdvp-`

|===
Der `solidfire-san` Der Treiber unterstützt Docker Swarm nicht.



=== Beispiel einer Element-Softwarekonfigurationsdatei

[source, json]
----
{
  "version": 1,
  "storageDriverName": "solidfire-san",
  "Endpoint": "https://admin:admin@192.168.160.3/json-rpc/8.0",
  "SVIP": "10.0.0.7:3260",
  "TenantName": "docker",
  "InitiatorIFace": "default",
  "Types": [
    {
      "Type": "Bronze",
      "Qos": {
        "minIOPS": 1000,
        "maxIOPS": 2000,
        "burstIOPS": 4000
      }
    },
    {
      "Type": "Silver",
      "Qos": {
        "minIOPS": 4000,
        "maxIOPS": 6000,
        "burstIOPS": 8000
      }
    },
    {
      "Type": "Gold",
      "Qos": {
        "minIOPS": 6000,
        "maxIOPS": 8000,
        "burstIOPS": 10000
      }
    }
  ]
}
----