---
sidebar: sidebar 
permalink: trident-managing-k8s/upgrade-operator-overview.html 
keywords: upgrade, trident, operator, helm, controller, daemonset, node pods, rolling upgrade, zero downtime 
summary: Bevor Sie den Trident -Operator zum Aktualisieren von Trident verwenden, sollten Sie die Hintergrundprozesse verstehen, die während der Aktualisierung ablaufen.  Dies umfasst Änderungen am Trident -Controller, Controller-Pod und Node-Pods sowie am Node-DaemonSet, die Rolling Updates ermöglichen. 
---
= Den Workflow für die Bediener-Upgrades verstehen
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie den Trident -Operator zum Aktualisieren von Trident verwenden, sollten Sie die Hintergrundprozesse verstehen, die während der Aktualisierung ablaufen.  Dies umfasst Änderungen am Trident -Controller, Controller-Pod und Node-Pods sowie am Node-DaemonSet, die Rolling Updates ermöglichen.



== Trident -Bedienungs-Upgrade-Handhabung

Einer der vielenlink:../trident-get-started/kubernetes-deploy.html["Vorteile der Verwendung des Trident Bedienelements"] Die Installation und Aktualisierung von Trident umfasst die automatische Handhabung von Trident und Kubernetes-Objekten, ohne bestehende eingebundene Volumes zu beeinträchtigen.  Auf diese Weise kann Trident Upgrades ohne Ausfallzeiten unterstützen, oderlink:https://kubernetes.io/docs/tutorials/kubernetes-basics/update/update-intro/["_laufende Aktualisierungen_"^] .  Insbesondere kommuniziert der Trident -Operator mit dem Kubernetes-Cluster, um:

* Löschen und erstellen Sie die Trident Controller-Bereitstellung und den Knoten-DaemonSet neu.
* Ersetzen Sie den Trident Controller Pod und die Trident Node Pods durch neue Versionen.
+
** Wenn ein Knoten nicht aktualisiert wird, hindert dies die Aktualisierung der übrigen Knoten nicht.
** Nur Knoten mit einem laufenden Trident Node Pod können Volumes einbinden.





TIP: Weitere Informationen zur Trident -Architektur im Kubernetes-Cluster finden Sie unter:link:../trident-get-started/architecture.html["Trident -Architektur"^] .



== Workflow zur Bediener-Upgrade

Wenn Sie ein Upgrade mit dem Trident -Operator starten:

. Der * Trident -Operator*:
+
.. Erkennt die aktuell installierte Version von Trident (Version _n_).
.. Aktualisiert alle Kubernetes-Objekte einschließlich CRDs, RBAC und Trident SVC.
.. Löscht die Trident Controller-Bereitstellung für Version _n_.
.. Erstellt die Trident Controller-Bereitstellung für Version _n+1_.


. *Kubernetes* erstellt Trident Controller Pod für _n+1_.
. Der * Trident -Operator*:
+
.. Löscht das Trident Node DaemonSet für _n_.  Der Operator wartet nicht auf die Beendigung des Node Pods.
.. Erstellt das Trident Node Daemonset für _n+1_.


. *Kubernetes* erstellt Trident Node Pods auf Knoten, auf denen kein Trident Node Pod _n_ ausgeführt wird.  Dadurch wird sichergestellt, dass sich auf einem Knoten niemals mehr als ein Trident Node Pod, unabhängig von der Version, befindet.

