---
sidebar: sidebar 
permalink: trident-use/backends.html 
keywords: backends, storage system, anf, cvs for gcp, element, hci, solidfire, ontap, aff, fas, ontap select, configure backends, fsx 
summary: Ein Backend definiert die Beziehung zwischen Trident und einem Speichersystem.  Es teilt Trident mit, wie mit diesem Speichersystem kommuniziert werden soll und wie Trident Datenträger daraus bereitstellen soll. 
---
= Backends konfigurieren
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ein Backend definiert die Beziehung zwischen Trident und einem Speichersystem.  Es teilt Trident mit, wie mit diesem Speichersystem kommuniziert werden soll und wie Trident Datenträger daraus bereitstellen soll.

Trident bietet automatisch Speicherpools von Backends an, die den Anforderungen einer Speicherklasse entsprechen.  Erfahren Sie, wie Sie das Backend für Ihr Speichersystem konfigurieren.

* link:anf.html["Konfigurieren eines Azure NetApp Files -Backends"^]
* link:gcnv.html["Konfigurieren eines Google Cloud NetApp Volumes -Backends"^]
* link:gcp.html["Konfigurieren eines Cloud Volumes Service für das Google Cloud Platform-Backend"^]
* link:element.html["Konfigurieren Sie ein NetApp HCI oder SolidFire Backend"^]
* link:ontap-nas.html["Konfigurieren Sie ein Backend mit ONTAP oder Cloud Volumes ONTAP NAS-Treibern"^]
* link:ontap-san.html["Konfigurieren Sie ein Backend mit ONTAP oder Cloud Volumes ONTAP SAN-Treibern"^]
* link:trident-fsx.html["Trident mit Amazon FSx for NetApp ONTAP verwenden"^]

