---
sidebar: sidebar 
permalink: trident-use/gcnv.html 
keywords: trident backend, google cloud netapp volumes, nfs volumes, nfs, drivers, access modes, rwo, rwx, rwp, rwop, file system, gke, cloud identity, google cloud 
summary:  
---
= Konfigurieren eines Google Cloud NetApp Volumes -Backends
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können jetzt Google Cloud NetApp Volumes als Backend für Trident konfigurieren.  Sie können NFS- und SMB-Volumes über ein Google Cloud NetApp Volumes -Backend einbinden.



== Details zum Google Cloud NetApp Volumes -Treiber

Trident bietet die `google-cloud-netapp-volumes` Der Treiber soll mit dem Cluster kommunizieren.  Unterstützte Zugriffsmodi sind: _ReadWriteOnce_ (RWO), _ReadOnlyMany_ (ROX), _ReadWriteMany_ (RWX), _ReadWriteOncePod_ (RWOP).

[cols="2, 1, 1, 2, 2"]
|===
| Treiber | Protokoll | Lautstärkemodus | Unterstützte Zugriffsmodi | Unterstützte Dateisysteme 


| `google-cloud-netapp-volumes`  a| 
NFS SMB
 a| 
Dateisystem
 a| 
RWO, ROX, RWX, RWOP
 a| 
`nfs`, `smb`

|===


== Cloud-Identität für GKE

Cloud Identity ermöglicht es Kubernetes-Pods, auf Google Cloud-Ressourcen zuzugreifen, indem sie sich als Workload-Identität authentifizieren, anstatt explizite Google Cloud-Anmeldeinformationen anzugeben.

Um die Cloud-Identität in Google Cloud nutzen zu können, benötigen Sie Folgendes:

* Ein mit GKE bereitgestellter Kubernetes-Cluster.
* Die Workload-Identität wurde im GKE-Cluster konfiguriert und der GKE MetaData Server auf den Knotenpools.
* Ein GCP-Dienstkonto mit der Rolle „Google Cloud NetApp Volumes Admin“ (roles/netapp.admin) oder einer benutzerdefinierten Rolle.
* Trident wurde installiert, einschließlich des Cloud-Providers, der "GCP" angibt, und der Cloud-Identität, die das neue GCP-Dienstkonto angibt.  Nachfolgend ein Beispiel.
+
[role="tabbed-block"]
====
.Trident -Betreiber
--
Um Trident mithilfe des Trident -Operators zu installieren, bearbeiten Sie `tridentorchestrator_cr.yaml` einstellen `cloudProvider` Zu `"GCP"` und setzen `cloudIdentity` Zu `iam.gke.io/gcp-service-account: \cloudvolumes-admin-sa@mygcpproject.iam.gserviceaccount.com` .

Beispiel:

[source, yaml]
----
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  imagePullPolicy: IfNotPresent
  cloudProvider: "GCP"
  cloudIdentity: 'iam.gke.io/gcp-service-account: cloudvolumes-admin-sa@mygcpproject.iam.gserviceaccount.com'
----
--
.Helm
--
Legen Sie die Werte für die Flags *cloud-provider (CP)* und *cloud-identity (CI)* mithilfe der folgenden Umgebungsvariablen fest:

`export CP="GCP"`
`export ANNOTATION="'iam.gke.io/gcp-service-account: \cloudvolumes-admin-sa@mygcpproject.iam.gserviceaccount.com'"`

Das folgende Beispiel installiert Trident und konfiguriert es. `cloudProvider` für GCP unter Verwendung der Umgebungsvariablen `$CP` und stellt die `cloudIdentity` unter Verwendung der Umgebungsvariablen `$ANNOTATION` :

[listing]
----
helm install trident trident-operator-100.6.0.tgz --set cloudProvider=$CP --set cloudIdentity="$ANNOTATION"
----
--
.<code>tridentctl</code>
--
Legen Sie die Werte für die Flags *Cloud-Anbieter* und *Cloud-Identität* mithilfe der folgenden Umgebungsvariablen fest:

`export CP="GCP"`
`export ANNOTATION="'iam.gke.io/gcp-service-account: \cloudvolumes-admin-sa@mygcpproject.iam.gserviceaccount.com'"`

Das folgende Beispiel installiert Trident und konfiguriert die `cloud-provider` Flagge an `$CP` , Und `cloud-identity` Zu `$ANNOTATION` :

[listing]
----
tridentctl install --cloud-provider=$CP --cloud-identity="$ANNOTATION" -n trident
----
--
====

