---
sidebar: sidebar 
permalink: trident-use/trident-fsx.html 
keywords: Amazon FSx for NetApp ONTAP, FSx for ONTAP, deploy Trident, integrate Trident, Trident 
summary: 'Durch die Verwendung von Trident mit Amazon FSx for NetApp ONTAP können Sie sicherstellen, dass Ihre Kubernetes-Cluster, die im Amazon Elastic Kubernetes Service (EKS) ausgeführt werden, persistente Block- und Dateivolumes bereitstellen können, die von ONTAP unterstützt werden.' 
---
= Trident mit Amazon FSx for NetApp ONTAP verwenden
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Amazon FSx for NetApp ONTAP"^]ist ein vollständig verwalteter AWS-Service, der es Kunden ermöglicht, Dateisysteme zu starten und auszuführen, die auf dem Speicherbetriebssystem NetApp ONTAP basieren.  FSx for ONTAP ermöglicht es Ihnen, die Ihnen vertrauten Funktionen, die Leistung und die administrativen Möglichkeiten von NetApp zu nutzen und gleichzeitig die Einfachheit, Agilität, Sicherheit und Skalierbarkeit der Datenspeicherung auf AWS in Anspruch zu nehmen.  FSx für ONTAP unterstützt die Funktionen des ONTAP -Dateisystems und die Administrations-APIs.

Sie können Ihr Amazon FSx for NetApp ONTAP Dateisystem mit Trident integrieren, um sicherzustellen, dass Kubernetes-Cluster, die im Amazon Elastic Kubernetes Service (EKS) ausgeführt werden, persistente Block- und Dateivolumes bereitstellen können, die von ONTAP unterstützt werden.

Das Dateisystem ist die primäre Ressource in Amazon FSx, analog zu einem ONTAP Cluster vor Ort.  Innerhalb jeder SVM können Sie ein oder mehrere Volumes erstellen. Dabei handelt es sich um Datencontainer, in denen die Dateien und Ordner Ihres Dateisystems gespeichert werden.  Mit Amazon FSx for NetApp ONTAP wird ein verwaltetes Dateisystem in der Cloud bereitgestellt.  Der neue Dateisystemtyp heißt * NetApp ONTAP*.

Durch die Verwendung von Trident mit Amazon FSx for NetApp ONTAP können Sie sicherstellen, dass Kubernetes-Cluster, die im Amazon Elastic Kubernetes Service (EKS) ausgeführt werden, persistente Block- und Dateivolumes bereitstellen können, die von ONTAP unterstützt werden.



== Anforderungen

Zusätzlich zulink:../trident-get-started/requirements.html["Trident Anforderungen"] Um FSx für ONTAP mit Trident zu integrieren, benötigen Sie:

* Ein bestehender Amazon EKS-Cluster oder ein selbstverwalteter Kubernetes-Cluster mit `kubectl` installiert.
* Ein vorhandenes Amazon FSx for NetApp ONTAP Dateisystem und eine Storage Virtual Machine (SVM), die von den Worker-Knoten Ihres Clusters aus erreichbar ist.
* Worker-Knoten, die vorbereitet sind fürlink:worker-node-prep.html["NFS oder iSCSI"] .
+

NOTE: Stellen Sie sicher, dass Sie die für Amazon Linux und Ubuntu erforderlichen Schritte zur Knotenvorbereitung befolgen. https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AMIs.html["Amazon Machine Images"^] (AMIs) abhängig von Ihrem EKS-AMI-Typ.





== Überlegungen

* SMB-Volumes:
+
** SMB-Volumes werden mithilfe von `ontap-nas` Nur für den Fahrer.
** SMB-Volumes werden vom Trident EKS-Add-on nicht unterstützt.
** Trident unterstützt SMB-Volumes nur, wenn sie in Pods eingebunden sind, die auf Windows-Knoten laufen. Siehe link:../trident-use/trident-fsx-storage-backend.html#prepare-to-provision-smb-volumes["Bereiten Sie die Bereitstellung von SMB-Volumes vor"] für Details.


* Vor Trident 24.02 konnten Volumes, die auf Amazon FSx Dateisystemen mit aktivierter automatischer Datensicherung erstellt wurden, von Trident nicht gelöscht werden.  Um dieses Problem in Trident 24.02 oder höher zu vermeiden, geben Sie Folgendes an: `fsxFilesystemID` AWS `apiRegion` AWS `apikey` und AWS `secretKey` in der Backend-Konfigurationsdatei für AWS FSx für ONTAP.
+

NOTE: Wenn Sie Trident eine IAM-Rolle zuweisen, können Sie die Angabe der `apiRegion` , `apiKey` , Und `secretKey` Felder explizit an Trident übergeben.  Weitere Informationen finden Sie unterlink:../trident-use/trident-fsx-examples.html["FSx für ONTAP: Konfigurationsoptionen und Beispiele"] .





=== Gleichzeitige Nutzung von Trident SAN/iSCSI und EBS-CSI-Treiber

Wenn Sie Ontap-San-Treiber (z. B. iSCSI) mit AWS (EKS, ROSA, EC2 oder einer anderen Instanz) verwenden möchten, kann es bei der auf den Knoten erforderlichen Multipath-Konfiguration zu Konflikten mit dem CSI-Treiber von Amazon Elastic Block Store (EBS) kommen. Um sicherzustellen, dass Multipathing funktioniert, ohne EBS-Festplatten auf demselben Knoten zu beeinträchtigen, müssen Sie EBS aus Ihrem Multipathing-Setup ausschließen. Dieses Beispiel zeigt ein `multipath.conf` Datei, die die erforderlichen Trident Einstellungen enthält und gleichzeitig EBS-Festplatten vom Multipathing ausschließt:

[listing]
----
defaults {
    find_multipaths no
}
blacklist {
    device {
        vendor "NVME"
        product "Amazon Elastic Block Store"
    }
}
----


== Authentifizierung

Trident bietet zwei Authentifizierungsmodi an.

* Anmeldeinformationsbasiert (Empfohlen): Speichert Anmeldeinformationen sicher im AWS Secrets Manager.  Sie können die `fsxadmin` Benutzer für Ihr Dateisystem oder die `vsadmin` Benutzerkonfiguriert für Ihre SVM.
+

WARNING: Trident geht davon aus, als ein `vsadmin` SVM-Benutzer oder als Benutzer mit einem anderen Namen, der die gleiche Rolle hat.  Amazon FSx for NetApp ONTAP hat ein `fsxadmin` Benutzer, der einen eingeschränkten Ersatz für ONTAP darstellt. `admin` Clusterbenutzer.  Wir empfehlen dringend die Verwendung `vsadmin` mit Trident.

* Zertifikatsbasiert: Trident kommuniziert mit der SVM auf Ihrem FSx-Dateisystem mithilfe eines auf Ihrer SVM installierten Zertifikats.


Einzelheiten zur Aktivierung der Authentifizierung finden Sie in der Dokumentation zur Authentifizierung für Ihren Treibertyp:

* link:ontap-nas-prep.html["ONTAP NAS-Authentifizierung"]
* link:ontap-san-prep.html["ONTAP SAN-Authentifizierung"]




== Getestete Amazon Machine Images (AMIs)

Der EKS-Cluster unterstützt verschiedene Betriebssysteme, aber AWS hat bestimmte Amazon Machine Images (AMIs) für Container und EKS optimiert.  Die folgenden AMIs wurden mit NetApp Trident 25.02 getestet.

|===


| AMI | NAS | NAS-Wirtschaft | iSCSI | iSCSI-Economy 


| AL2023_x86_64_STANDARD | Ja | Ja | Ja | Ja 


| AL2_x86_64 | Ja | Ja | Ja* | Ja* 


| BOTTLEROCKET_x86_64 | Ja** | Ja | k. A. | k. A. 


| AL2023_ARM_64_STANDARD | Ja | Ja | Ja | Ja 


| AL2_ARM_64 | Ja | Ja | Ja* | Ja* 


| BOTTLEROCKET_ARM_64 | Ja** | Ja | k. A. | k. A. 
|===
* * Das Löschen des PV ist ohne Neustart des Knotens nicht möglich
* ** Funktioniert nicht mit NFSv3 mit Trident Version 25.02.



NOTE: Wenn Ihr gewünschtes AMI hier nicht aufgeführt ist, bedeutet das nicht, dass es nicht unterstützt wird; es bedeutet lediglich, dass es nicht getestet wurde.  Diese Liste dient als Leitfaden für AMIs, von denen bekannt ist, dass sie funktionieren.

*Tests durchgeführt mit*:

* EKS-Version: 1.32
* Installationsmethode: Helm 25.06 und als AWS-Add-On 25.06
* Für NAS wurden sowohl NFSv3 als auch NFSv4.1 getestet.
* Für SAN wurde nur iSCSI getestet, nicht NVMe-oF.


*Durchgeführte Tests*:

* Erstellen: Speicherklasse, PVC, Kapsel
* Löschen: Pod, PVC (regulär, Qtree/LUN – Economy, NAS mit AWS-Backup)




== Weitere Informationen

* https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Amazon FSx for NetApp ONTAP -Dokumentation"^]
* https://www.netapp.com/blog/amazon-fsx-for-netapp-ontap/["Blogbeitrag über Amazon FSx for NetApp ONTAP"^]

