---
sidebar: sidebar 
permalink: trident-use/trident-fsx-install-trident.html 
keywords: Amazon FSx for NetApp ONTAP, FSx for ONTAP, deploy Trident, integrate Trident, Trident add-on, Trident EKS add-on, Trident AWS EKS add-on 
summary: 'Durch die Verwendung von Trident mit Amazon FSx for NetApp ONTAP können Sie sicherstellen, dass Ihre Kubernetes-Cluster, die im Amazon Elastic Kubernetes Service (EKS) ausgeführt werden, persistente Block- und Dateivolumes bereitstellen können, die von ONTAP unterstützt werden.' 
---
= Trident installieren
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Trident optimiert die Amazon FSx for NetApp ONTAP in Kubernetes, damit sich Ihre Entwickler und Administratoren auf die Anwendungsbereitstellung konzentrieren können.

Sie können Trident mit einer der folgenden Methoden installieren:

* Helm
* EKS-Add-on


Wenn Sie die Snapshot-Funktionalität nutzen möchten, installieren Sie das CSI Snapshot Controller Add-on.  Siehelink:https://docs.aws.amazon.com/eks/latest/userguide/csi-snapshot-controller.html["Snapshot-Funktionalität für CSI-Volumes aktivieren"^] für weitere Informationen.



== Installieren Sie Trident über Helm

[role="tabbed-block"]
====
.Pod-Identität
--
. Fügen Sie das Trident Helm-Repository hinzu:
+
[source, console]
----
helm repo add netapp-trident https://netapp.github.io/trident-helm-chart
----
. Installieren Sie Trident anhand des folgenden Beispiels:
+
[source, console]
----
helm install trident-operator netapp-trident/trident-operator --version 100.2502.1 --namespace trident --create-namespace
----
+
Sie können die `helm list` Befehl zum Überprüfen von Installationsdetails wie Name, Namespace, Chart, Status, App-Version und Revisionsnummer.

+
[source, console]
----
helm list -n trident
----
+
[listing]
----
NAME                NAMESPACE   REVISION    UPDATED                                 STATUS       CHART                          APP VERSION

trident-operator    trident     1           2024-10-14 14:31:22.463122 +0300 IDT    deployed     trident-operator-100.2502.0    25.02.0
----


--
.Servicekonto-Zuordnung (IRSA)
--
. Fügen Sie das Trident Helm-Repository hinzu:
+
[source, console]
----
helm repo add netapp-trident https://netapp.github.io/trident-helm-chart
----
. Legen Sie die Werte für *Cloud-Anbieter* und *Cloud-Identität* fest:
+
[source, console]
----
helm install trident-operator netapp-trident/trident-operator --version 100.2502.1  \
--set cloudProvider="AWS" \
--set cloudIdentity="'eks.amazonaws.com/role-arn: arn:aws:iam::<accountID>:role/<AmazonEKS_FSxN_CSI_DriverRole>'" \
--namespace trident \
--create-namespace
----
+
Sie können die `helm list` Befehl zum Überprüfen von Installationsdetails wie Name, Namespace, Chart, Status, App-Version und Revisionsnummer.

+
[source, console]
----
helm list -n trident
----
+
[listing]
----
NAME                NAMESPACE   REVISION    UPDATED                                 STATUS       CHART                          APP VERSION

trident-operator    trident     1           2024-10-14 14:31:22.463122 +0300 IDT    deployed     trident-operator-100.2506.0    25.06.0
----


--
====
[NOTE]
====
Wenn Sie iSCSI verwenden möchten, stellen Sie sicher, dass iSCSI auf Ihrem Client-Rechner aktiviert ist.  Wenn Sie AL2023 Worker Node OS verwenden, können Sie die Installation des iSCSI-Clients automatisieren, indem Sie den Parameter „node prep“ in die Helm-Installation einfügen:

[source, console]
----
helm install trident-operator netapp-trident/trident-operator --version 100.2502.1 --namespace trident --create-namespace –-set nodePrep={iscsi}
----
====


== Installieren Sie Trident über das EKS-Add-on

Das Trident EKS-Add-on enthält die neuesten Sicherheitspatches und Fehlerbehebungen und ist von AWS für die Verwendung mit Amazon EKS validiert.  Mit dem EKS-Add-on können Sie sicherstellen, dass Ihre Amazon EKS-Cluster stets sicher und stabil sind und den Aufwand für die Installation, Konfiguration und Aktualisierung von Add-ons reduzieren.



=== Voraussetzungen

Stellen Sie sicher, dass Sie Folgendes haben, bevor Sie das Trident Add-on für AWS EKS konfigurieren:

* Ein Amazon EKS-Clusterkonto mit Zusatzabonnement
* AWS-Berechtigungen für den AWS Marketplace:
`"aws-marketplace:ViewSubscriptions",
"aws-marketplace:Subscribe",
"aws-marketplace:Unsubscribe`
* AMI-Typ: Amazon Linux 2 (AL2_x86_64) oder Amazon Linux 2 Arm (AL2_ARM_64)
* Knotentyp: AMD oder ARM
* Ein bestehendes Amazon FSx for NetApp ONTAP Dateisystem




=== Aktivieren Sie das Trident Add-on für AWS.

[role="tabbed-block"]
====
.Verwaltungskonsole
--
. Öffnen Sie die Amazon EKS-Konsole unter https://console.aws.amazon.com/eks/home#/clusters[] .
. Im linken Navigationsbereich wählen Sie *Cluster* aus.
. Wählen Sie den Namen des Clusters aus, für den Sie das NetApp Trident CSI-Add-on konfigurieren möchten.
. Wählen Sie *Add-ons* und anschließend *Weitere Add-ons abrufen*.
. Gehen Sie wie folgt vor, um das Add-on auszuwählen:
+
.. Scrollen Sie nach unten zum Abschnitt *AWS Marketplace Add-ons* und geben Sie *"Trident"* in das Suchfeld ein.
.. Aktivieren Sie das Kontrollkästchen in der oberen rechten Ecke des Feldes „Trident by NetApp“ .
.. Wählen Sie *Weiter*.


. Gehen Sie auf der Einstellungsseite *Ausgewählte Add-ons konfigurieren* wie folgt vor:
+

NOTE: *Überspringen Sie diese Schritte, wenn Sie die Pod Identity-Zuordnung verwenden.*

+
.. Wählen Sie die *Version* aus, die Sie verwenden möchten.
.. Wenn Sie die IRSA-Authentifizierung verwenden, stellen Sie sicher, dass Sie die in den optionalen Konfigurationseinstellungen verfügbaren Konfigurationswerte festlegen:
+
*** Wählen Sie die *Version* aus, die Sie verwenden möchten.
*** Folgen Sie dem *Add-on-Konfigurationsschema* und legen Sie den Parameter *configurationValues* im Abschnitt *Konfigurationswerte* auf den Rollen-ARN fest, den Sie im vorherigen Schritt erstellt haben (der Wert sollte folgendes Format haben):




+
[source, JSON]
----
{

  "cloudIdentity": "'eks.amazonaws.com/role-arn: <role ARN>'",
  "cloudProvider": "AWS"

}
----
+
Wenn Sie bei der Konfliktlösungsmethode die Option „Überschreiben“ auswählen, können eine oder mehrere Einstellungen des bestehenden Add-ons mit den Einstellungen des Amazon EKS-Add-ons überschrieben werden.  Wenn Sie diese Option nicht aktivieren und es zu einem Konflikt mit Ihren bestehenden Einstellungen kommt, schlägt der Vorgang fehl.  Sie können die resultierende Fehlermeldung zur Fehlerbehebung des Konflikts verwenden.  Bevor Sie diese Option auswählen, vergewissern Sie sich, dass das Amazon EKS-Add-on keine Einstellungen verwaltet, die Sie selbst verwalten müssen.

. Wählen Sie *Weiter*.
. Auf der Seite *Überprüfen und hinzufügen* wählen Sie *Erstellen*.
+
Nach Abschluss der Add-on-Installation wird Ihnen das installierte Add-on angezeigt.



--
.AWS CLI
--
*1. Erstellen Sie die `add-on.json` Datei*:

*Für die Pod-Identität verwenden Sie bitte folgendes Format*:

[source, json]
----
{
  "clusterName": "<eks-cluster>",
  "addonName": "netapp_trident-operator",
  "addonVersion": "v25.6.0-eksbuild.1",
}
----
*Für die IRSA-Authentifizierung verwenden Sie bitte folgendes Format*:

[source, json]
----
{
  "clusterName": "<eks-cluster>",
  "addonName": "netapp_trident-operator",
  "addonVersion": "v25.6.0-eksbuild.1",
  "serviceAccountRoleArn": "<role ARN>",
  "configurationValues": {
    "cloudIdentity": "'eks.amazonaws.com/role-arn: <role ARN>'",
    "cloudProvider": "AWS"
  }
}
----

NOTE: Ersetzen `<role ARN>` mit dem ARN der Rolle, die im vorherigen Schritt erstellt wurde.

*2. Installieren Sie das Trident EKS-Add-on.*

[source, console]
----
aws eks create-addon --cli-input-json file://add-on.json
----
--
.eksctl
--
Der folgende Beispielbefehl installiert das Trident EKS-Add-on:

[source, console]
----
eksctl create addon --name netapp_trident-operator --cluster <cluster_name> --force
----
--
====


=== Aktualisieren Sie das Trident EKS-Add-on

[role="tabbed-block"]
====
.Verwaltungskonsole
--
. Öffnen Sie die Amazon EKS-Konsole. https://console.aws.amazon.com/eks/home#/clusters[] .
. Im linken Navigationsbereich wählen Sie *Cluster* aus.
. Wählen Sie den Namen des Clusters aus, für den Sie das NetApp Trident CSI-Add-on aktualisieren möchten.
. Wählen Sie den Reiter *Add-ons*.
. Wählen Sie * Trident by NetApp* und anschließend *Bearbeiten*.
. Führen Sie auf der Seite * Trident von NetApp konfigurieren* folgende Schritte aus:
+
.. Wählen Sie die *Version* aus, die Sie verwenden möchten.
.. Erweitern Sie die *Optionalen Konfigurationseinstellungen* und nehmen Sie bei Bedarf Anpassungen vor.
.. Wählen Sie *Änderungen speichern*.




--
.AWS CLI
--
Das folgende Beispiel aktualisiert das EKS-Add-on:

[source, console]
----
aws eks update-addon --cluster-name <eks_cluster_name> --addon-name netapp_trident-operator --addon-version v25.6.0-eksbuild.1 \
  --service-account-role-arn <role-ARN> --resolve-conflict preserve \
  --configuration-values “{\"cloudIdentity\": \"'eks.amazonaws.com/role-arn: <role ARN>'\"}"
----
--
.eksctl
--
* Überprüfen Sie die aktuelle Version Ihres FSxN Trident CSI-Add-ons.  Ersetzen `my-cluster` mit Ihrem Clusternamen.
+
[source, console]
----
eksctl get addon --name netapp_trident-operator --cluster my-cluster
----
+
*Beispielausgabe:*



[listing]
----
NAME                        VERSION             STATUS    ISSUES    IAMROLE    UPDATE AVAILABLE    CONFIGURATION VALUES
netapp_trident-operator    v25.6.0-eksbuild.1    ACTIVE    0       {"cloudIdentity":"'eks.amazonaws.com/role-arn: arn:aws:iam::139763910815:role/AmazonEKS_FSXN_CSI_DriverRole'"}
----
* Aktualisieren Sie das Add-on auf die Version, die im Ergebnis des vorherigen Schritts unter UPDATE AVAILABLE angezeigt wurde.
+
[source, console]
----
eksctl update addon --name netapp_trident-operator --version v25.6.0-eksbuild.1 --cluster my-cluster --force
----


Wenn Sie die `--force` Wenn eine der Optionen und eine der Einstellungen des Amazon EKS-Add-ons mit Ihren bestehenden Einstellungen in Konflikt steht und das Aktualisieren des Amazon EKS-Add-ons fehlschlägt, erhalten Sie eine Fehlermeldung, die Ihnen bei der Behebung des Konflikts hilft.  Bevor Sie diese Option angeben, vergewissern Sie sich, dass das Amazon EKS-Add-on keine Einstellungen verwaltet, die Sie selbst verwalten müssen, da diese Einstellungen durch diese Option überschrieben werden.  Weitere Informationen zu anderen Optionen für diese Einstellung finden Sie unterlink:https://eksctl.io/usage/addons/["Addons"] .  Weitere Informationen zur Feldverwaltung von Amazon EKS Kubernetes finden Sie unterlink:https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-field-management.html["Kubernetes-Feldmanagement"] .

--
====


=== Deinstallieren/entfernen Sie das Trident EKS-Add-on.

Sie haben zwei Möglichkeiten, ein Amazon EKS-Add-on zu entfernen:

* *Zusatzsoftware auf Ihrem Cluster beibehalten* – Diese Option entfernt die Verwaltung aller Einstellungen durch Amazon EKS.  Außerdem entfällt dadurch die Möglichkeit für Amazon EKS, Sie über Aktualisierungen zu benachrichtigen und das Amazon EKS-Add-on automatisch zu aktualisieren, nachdem Sie eine Aktualisierung initiiert haben.  Die Zusatzsoftware auf Ihrem Cluster bleibt jedoch erhalten.  Diese Option macht das Add-on zu einer selbstverwalteten Installation und nicht zu einem Amazon EKS-Add-on.  Bei dieser Option gibt es keine Ausfallzeiten für das Add-on.  Behalten Sie die `--preserve` Option im Befehl zum Beibehalten des Add-ons.
* *Entfernen Sie die Add-on-Software vollständig aus Ihrem Cluster* – NetApp empfiehlt, das Amazon EKS-Add-on nur dann aus Ihrem Cluster zu entfernen, wenn keine Ressourcen in Ihrem Cluster davon abhängig sind.  Entfernen Sie die `--preserve` Option aus der `delete` Befehl zum Entfernen des Add-ons.



NOTE: Wenn dem Add-on ein IAM-Konto zugeordnet ist, wird das IAM-Konto nicht entfernt.

[role="tabbed-block"]
====
.Verwaltungskonsole
--
. Öffnen Sie die Amazon EKS-Konsole unter https://console.aws.amazon.com/eks/home#/clusters[] .
. Im linken Navigationsbereich wählen Sie *Cluster* aus.
. Wählen Sie den Namen des Clusters aus, für den Sie das NetApp Trident CSI-Add-on entfernen möchten.
. Wählen Sie die Registerkarte *Add-ons* und anschließend * Trident by NetApp*.
. Wählen Sie *Entfernen*.
. Führen Sie im Dialogfeld „Bestätigung zum Entfernen des netapp_trident-Operators“ folgende Schritte aus:
+
.. Wenn Sie nicht möchten, dass Amazon EKS die Einstellungen für das Add-on verwaltet, wählen Sie *Auf Cluster beibehalten*.  Tun Sie dies, wenn Sie die Zusatzsoftware auf Ihrem Cluster behalten möchten, um alle Einstellungen des Zusatzes selbst verwalten zu können.
.. Geben Sie *netapp_trident-operator* ein.
.. Wählen Sie *Entfernen*.




--
.AWS CLI
--
Ersetzen `my-cluster` mit dem Namen Ihres Clusters und führen Sie dann den folgenden Befehl aus.

[source, console]
----
aws eks delete-addon --cluster-name my-cluster --addon-name netapp_trident-operator --preserve
----
--
.eksctl
--
Der folgende Befehl deinstalliert das Trident EKS-Add-on:

[source, console]
----
eksctl delete addon --cluster K8s-arm --name netapp_trident-operator
----
--
====