---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-deploy-helm.html 
keywords: deploy, Trident, operator, helm, helm chart, configuration, values, standard, registry 
summary: Sie können den Trident -Operator bereitstellen und Trident mithilfe von Helm installieren.  Dieser Prozess kommt bei Installationen zum Einsatz, bei denen die von Trident benötigten Container-Images nicht in einer privaten Registry gespeichert sind. 
---
= Trident -Operator mit Helm bereitstellen (Standardmodus)
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können den Trident -Operator bereitstellen und Trident mithilfe von Helm installieren.  Dieser Prozess kommt bei Installationen zum Einsatz, bei denen die von Trident benötigten Container-Images nicht in einer privaten Registry gespeichert sind.  Falls Sie über eine private Bildregistrierung verfügen, verwenden Sie dielink:kubernetes-deploy-helm-mirror.html["Prozess für die Offline-Bereitstellung"] .



== Wichtige Informationen zu Trident 25.06

*Sie müssen die folgenden wichtigen Informationen über Trident unbedingt lesen.*

.<strong>Wichtige Informationen zu Trident</strong>
[%collapsible%open]
====
[]
=====
* Kubernetes 1.34 wird jetzt in Trident unterstützt. Aktualisieren Sie Trident , bevor Sie Kubernetes aktualisieren.
* Trident setzt die Verwendung von Multipathing-Konfigurationen in SAN-Umgebungen strikt durch, mit einem empfohlenen Wert von `find_multipaths: no` in der Datei multipath.conf.
+
Verwendung einer Nicht-Multipathing-Konfiguration oder Verwendung von `find_multipaths: yes` oder `find_multipaths: smart` Ein falscher Wert in der Datei multipath.conf führt zu Mount-Fehlern.  Trident hat die Verwendung von `find_multipaths: no` seit der Version vom 21.07.



=====
====


== Den Trident -Operator bereitstellen und Trident mit Helm installieren

Den Trident benutzenlink:https://artifacthub.io/packages/helm/netapp-trident/trident-operator["Helm Chart"^] Sie können den Trident -Operator bereitstellen und Trident in einem Schritt installieren.

Rezensionlink:../trident-get-started/kubernetes-deploy.html["Installationsübersicht"] um sicherzustellen, dass Sie die Installationsvoraussetzungen erfüllt und die richtige Installationsoption für Ihre Umgebung ausgewählt haben.

.Bevor Sie beginnen
Zusätzlich zu denlink:../trident-get-started/kubernetes-deploy.html#before-you-deploy["Bereitstellungsvoraussetzungen"] Sie brauchenlink:https://v3.helm.sh/["Helm Version 3"^] .

.Schritte
. Fügen Sie das Trident Helm-Repository hinzu:
+
[listing]
----
helm repo add netapp-trident https://netapp.github.io/trident-helm-chart
----
. Verwenden `helm install` und geben Sie einen Namen für Ihre Bereitstellung an, wie im folgenden Beispiel, wobei `100.2506.0` ist die Version von Trident, die Sie installieren.
+
[listing]
----
helm install <name> netapp-trident/trident-operator --version 100.2506.0 --create-namespace --namespace <trident-namespace>
----
+

NOTE: Wenn Sie bereits einen Namespace für Trident erstellt haben, `--create-namespace` Der Parameter erzeugt keinen zusätzlichen Namensraum.



Sie können verwenden `helm list` Installationsdetails wie Name, Namespace, Chart, Status, App-Version und Revisionsnummer überprüfen.



== Konfigurationsdaten während der Installation übergeben

Es gibt zwei Möglichkeiten, Konfigurationsdaten während der Installation zu übergeben:

[cols="2"]
|===
| Option | Beschreibung 


| `--values`(oder `-f` )  a| 
Geben Sie eine YAML-Datei mit Überschreibungen an.  Dies kann mehrfach angegeben werden, wobei die am weitesten rechts stehende Datei Vorrang hat.



| `--set`  a| 
Überschreibungen müssen in der Befehlszeile angegeben werden.

|===
Um beispielsweise den Standardwert von `debug` Führen Sie den folgenden Befehl aus, wobei `100.2506.0` ist die Version von Trident, die Sie installieren:

[listing]
----
helm install <name> netapp-trident/trident-operator --version 100.2506.0  --create-namespace --namespace trident --set tridentDebug=true
----


== Konfigurationsoptionen

Diese Tabelle und die `values.yaml` Die Datei, die Teil des Helm-Charts ist, enthält die Liste der Schlüssel und ihrer Standardwerte.

[cols="1,2,3"]
|===
| Option | Beschreibung | Standard 


| `nodeSelector` | Knotenbezeichnungen für die Pod-Zuweisung |  


| `podAnnotations` | Pod-Anmerkungen |  


| `deploymentAnnotations` | Bereitstellungsanmerkungen |  


| `tolerations` | Toleranzen für die Pod-Zuordnung |  


| `affinity` | Affinität zur Pod-Zuweisung  a| 
[listing]
----
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
              - arm64
              - amd64
            - key: kubernetes.io/os
              operator: In
              values:
              - linux
----

WARNING: Die Standardaffinität darf nicht aus der Datei values.yaml entfernt werden.  Wenn Sie eine benutzerdefinierte Affinität bereitstellen möchten, erweitern Sie die Standardaffinität.



| `tridentControllerPluginNodeSelector` | Zusätzliche Knotenselektoren für Pods. Siehe <<Controller-Pods und Node-Pods verstehen>> für Details. |  


| `tridentControllerPluginTolerations` | Überschreibt die Kubernetes-Toleranzen für Pods. Siehe <<Controller-Pods und Node-Pods verstehen>> für Details. |  


| `tridentNodePluginNodeSelector` | Zusätzliche Knotenselektoren für Pods. Siehe <<Controller-Pods und Node-Pods verstehen>> für Details. |  


| `tridentNodePluginTolerations` | Überschreibt die Kubernetes-Toleranzen für Pods. Siehe <<Controller-Pods und Node-Pods verstehen>> für Details. |  


| `imageRegistry` | Identifiziert das Register für die `trident-operator` , `trident` und andere Bilder.  Lassen Sie das Feld leer, um die Standardeinstellung zu übernehmen.  WICHTIG: Bei der Installation von Trident in einem privaten Repository, falls Sie die `imageRegistry` Um den Speicherort des Repositorys anzugeben, verwenden Sie nicht `/netapp/` im Repository-Pfad. | `""` 


| `imagePullPolicy` | Legt die Image-Pull-Richtlinie für die `trident-operator` . | `IfNotPresent` 


| `imagePullSecrets` | Legt die Bildabrufgeheimnisse für die `trident-operator` , `trident` und andere Bilder. |  


| `kubeletDir` | Ermöglicht das Überschreiben des Host-Speicherorts des internen Zustands von kubelet. | `"/var/lib/kubelet"` 


| `operatorLogLevel` | Ermöglicht die Festlegung des Protokollierungslevels des Trident -Operators auf: `trace` , `debug` , `info` , `warn` , `error` , oder `fatal` . | `"info"` 


| `operatorDebug` | Ermöglicht es, den Protokollierungsgrad des Trident -Operators auf Debug zu setzen. | `true` 


| `operatorImage` | Ermöglicht das vollständige Überschreiben des Bildes für `trident-operator` . | `""` 


| `operatorImageTag` | Ermöglicht das Überschreiben des Tags von `trident-operator` Bild. | `""` 


| `tridentIPv6` | Ermöglicht die Nutzung von Trident in IPv6-Clustern. | `false` 


| `tridentK8sTimeout` | Überschreibt das standardmäßige Timeout von 30 Sekunden für die meisten Kubernetes-API-Operationen (falls ungleich Null, in Sekunden). | `0` 


| `tridentHttpRequestTimeout` | Überschreibt das standardmäßige Timeout von 90 Sekunden für HTTP-Anfragen, `0s` wobei die Auszeitdauer unendlich ist.  Negative Werte sind nicht zulässig. | `"90s"` 


| `tridentSilenceAutosupport` | Ermöglicht das Deaktivieren der periodischen AutoSupport Berichterstattung von Trident . | `false` 


| `tridentAutosupportImageTag` | Ermöglicht das Überschreiben des Tags des Bildes für den Trident AutoSupport Container. | `<version>` 


| `tridentAutosupportProxy` | Ermöglicht es dem Trident AutoSupport Container, über einen HTTP-Proxy eine Verbindung zum Server herzustellen. | `""` 


| `tridentLogFormat` | Legt das Trident Protokollierungsformat fest(`text` oder `json` ). | `"text"` 


| `tridentDisableAuditLog` | Deaktiviert den Trident -Audit-Logger. | `true` 


| `tridentLogLevel` | Ermöglicht die Festlegung des Protokollierungslevels von Trident auf: `trace` , `debug` , `info` , `warn` , `error` , oder `fatal` . | `"info"` 


| `tridentDebug` | Ermöglicht die Einstellung des Protokollierungslevels von Trident auf `debug` . | `false` 


| `tridentLogWorkflows` | Ermöglicht die Aktivierung bestimmter Trident -Workflows für die Protokollierung von Ablaufverfolgungen oder die Unterdrückung von Protokolldateien. | `""` 


| `tridentLogLayers` | Ermöglicht die Aktivierung bestimmter Trident -Ebenen für die Protokollierung von Ablaufverfolgungen oder die Unterdrückung von Protokolldateien. | `""` 


| `tridentImage` | Ermöglicht das vollständige Überschreiben des Images für Trident. | `""` 


| `tridentImageTag` | Ermöglicht das Überschreiben des Tags des Bildes für Trident. | `""` 


| `tridentProbePort` | Ermöglicht das Überschreiben des Standardports, der für Kubernetes Liveness-/Readiness-Probes verwendet wird. | `""` 


| `windows` | Ermöglicht die Installation von Trident auf einem Windows-Worker-Knoten. | `false` 


| `enableForceDetach` | Ermöglicht das Aktivieren der Funktion „Zwangstrennung“. | `false` 


| `excludePodSecurityPolicy` | Schließt die Erstellung der Sicherheitsrichtlinie für den Operator-Pod aus. | `false` 


| `cloudProvider` | Auf einstellen `"Azure"` bei der Verwendung von verwalteten Identitäten oder einer Cloud-Identität auf einem AKS-Cluster.  Bei Verwendung einer Cloud-Identität auf einem EKS-Cluster auf „AWS“ einstellen. | `""` 


| `cloudIdentity` | Setzen Sie die Workload-Identität auf ("azure.workload.identity/client-id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx"), wenn Sie Cloud Identity auf einem AKS-Cluster verwenden.  Setzen Sie die AWS IAM-Rolle auf ("eks.amazonaws.com/role-arn: arn:aws:iam::123456:role/trident-role"), wenn Sie Cloud Identity auf einem EKS-Cluster verwenden. | `""` 


| `iscsiSelfHealingInterval` | Das Intervall, in dem die iSCSI-Selbstheilung aufgerufen wird. | `5m0s` 


| `iscsiSelfHealingWaitTime` | Die Zeitspanne, nach der die iSCSI-Selbstheilung einen Versuch unternimmt, eine veraltete Sitzung durch Abmeldung und anschließende Anmeldung aufzulösen. | `7m0s` 


| `nodePrep` | Ermöglicht Trident , die Knoten des Kubernetes-Clusters für die Verwaltung von Volumes mithilfe des angegebenen Datenspeicherprotokolls vorzubereiten. *Momentan, `iscsi` ist der einzige unterstützte Wert.* HINWEIS: Ab OpenShift 4.19 ist die für diese Funktion unterstützte Mindestversion von Trident 25.06.1. |  


| `enableConcurrency`  a| 
Ermöglicht gleichzeitige Trident -Controller-Operationen für verbesserten Durchsatz.


NOTE: *Technische Vorschau*: Diese Funktion ist in NetApp Trident 25.06 experimentell und unterstützt derzeit begrenzte parallele Workflows mit dem ONTAP-SAN-Treiber (iSCSI- und FCP-Protokolle).
| FALSCH 


| `k8sAPIQPS`  a| 
Das vom Controller bei der Kommunikation mit dem Kubernetes-API-Server verwendete Limit für Abfragen pro Sekunde (QPS). Der Burst-Wert wird automatisch basierend auf dem QPS-Wert festgelegt.
| `100`; optional 
|===


=== Controller-Pods und Node-Pods verstehen

Trident läuft als ein einzelner Controller-Pod sowie als ein Node-Pod auf jedem Worker-Knoten im Cluster.  Der Node-Pod muss auf jedem Host ausgeführt werden, auf dem Sie möglicherweise ein Trident -Volume einbinden möchten.

Kuberneteslink:https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/["Knotenselektoren"^] Undlink:https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/["Toleranzen und Verunreinigungen"^] werden verwendet, um einen Pod so einzuschränken, dass er auf einem bestimmten oder bevorzugten Knoten ausgeführt wird.  Verwendung des `ControllerPlugin` und `NodePlugin` Sie können Einschränkungen und Überschreibungen festlegen.

* Das Controller-Plugin übernimmt die Bereitstellung und Verwaltung von Volumes, wie z. B. Snapshots und Größenänderungen.
* Das Node-Plugin kümmert sich um die Anbindung des Speichers an den Knoten.

