---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-deploy-tridentctl.html 
keywords: deploy, Trident, methods, tridentctl, windows 
summary: 'Sie können Trident installieren mit `tridentctl` .  Dieser Prozess gilt für Installationen, bei denen die von Trident benötigten Container-Images entweder in einer privaten Registry gespeichert sind oder nicht.' 
---
= Installation mit tridentctl
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Trident installieren mit `tridentctl` .  Dieser Prozess gilt für Installationen, bei denen die von Trident benötigten Container-Images entweder in einer privaten Registry gespeichert sind oder nicht.  Um Ihre `tridentctl` Bereitstellung, siehelink:kubernetes-customize-deploy-tridentctl.html["tridentctl-Bereitstellung anpassen"] .



== Wichtige Informationen zu Trident 25.06

*Sie müssen die folgenden wichtigen Informationen über Trident unbedingt lesen.*

.<strong>Wichtige Informationen zu Trident</strong>
[%collapsible%open]
====
* Kubernetes 1.27 wird jetzt in Trident unterstützt. Aktualisieren Sie Trident , bevor Sie Kubernetes aktualisieren.
* Trident setzt die Verwendung von Multipathing-Konfigurationen in SAN-Umgebungen strikt durch, mit einem empfohlenen Wert von `find_multipaths: no` in der Datei multipath.conf.
+
Verwendung einer Nicht-Multipathing-Konfiguration oder Verwendung von `find_multipaths: yes` oder `find_multipaths: smart` Ein falscher Wert in der Datei multipath.conf führt zu Mount-Fehlern.  Trident hat die Verwendung von `find_multipaths: no` seit der Version vom 21.07.



====


== Installieren Sie Trident mit `tridentctl`

Rezensionlink:../trident-get-started/kubernetes-deploy.html["Installationsübersicht"] um sicherzustellen, dass Sie die Installationsvoraussetzungen erfüllt und die richtige Installationsoption für Ihre Umgebung ausgewählt haben.

.Bevor Sie beginnen
Bevor Sie mit der Installation beginnen, melden Sie sich am Linux-Host an und vergewissern Sie sich, dass dieser ein funktionierendes System verwaltet.link:requirements.html["unterstützter Kubernetes-Cluster"^] und dass Sie über die notwendigen Berechtigungen verfügen.


NOTE: Mit OpenShift verwenden Sie `oc` anstatt `kubectl` Melden Sie sich in allen folgenden Beispielen zuerst als *system:admin* an, indem Sie folgenden Befehl ausführen `oc login -u system:admin` oder `oc login -u kube-admin` .

[%collapsible%open]
====
. Überprüfen Sie Ihre Kubernetes-Version:
+
[listing]
----
kubectl version
----
. Überprüfen Sie die Cluster-Administratorrechte:
+
[listing]
----
kubectl auth can-i '*' '*' --all-namespaces
----
. Überprüfen Sie, ob Sie einen Pod starten können, der ein Image von Docker Hub verwendet, und Ihr Speichersystem über das Pod-Netzwerk erreichen können:
+
[listing]
----
kubectl run -i --tty ping --image=busybox --restart=Never --rm -- \
  ping <management IP>
----


====


== Schritt 1: Laden Sie das Trident Installationspaket herunter

Das Trident -Installationspaket erstellt einen Trident Pod, konfiguriert die CRD-Objekte, die zur Aufrechterhaltung seines Zustands verwendet werden, und initialisiert die CSI-Sidecars, um Aktionen wie die Bereitstellung und das Anhängen von Volumes an die Cluster-Hosts durchzuführen.  Laden Sie die neueste Version des Trident -Installationsprogramms herunter und extrahieren Sie sie vonlink:https://github.com/NetApp/trident/releases/latest["der Abschnitt „Assets“ auf GitHub"^] .  Aktualisieren Sie _<trident-installer-XX.XX.X.tar.gz>_ im Beispiel mit Ihrer ausgewählten Trident Version.

[listing]
----
wget https://github.com/NetApp/trident/releases/download/v25.06.0/trident-installer-25.06.0.tar.gz
tar -xf trident-installer-25.06.0.tar.gz
cd trident-installer
----


== Schritt 2: Trident installieren

Installieren Sie Trident im gewünschten Namespace durch Ausführen des folgenden Befehls: `tridentctl install` Befehl.  Sie können zusätzliche Argumente hinzufügen, um den Speicherort der Bildregistrierung anzugeben.

[role="tabbed-block"]
====
.Standardmodus
--
[listing]
----
./tridentctl install -n trident
----
--
.Bilder in einem Register
--
[listing]
----
./tridentctl install -n trident --image-registry <your-registry> --autosupport-image <your-registry>/trident-autosupport:25.06 --trident-image <your-registry>/trident:25.06.0
----
--
.Bilder in verschiedenen Registern
--
[listing]
----
./tridentctl install -n trident --image-registry <your-registry> --autosupport-image <your-registry>/trident-autosupport:25.06 --trident-image <your-registry>/trident:25.06.0
----
--
====
Ihr Installationsstatus sollte in etwa so aussehen.

[listing]
----
....
INFO Starting Trident installation.                namespace=trident
INFO Created service account.
INFO Created cluster role.
INFO Created cluster role binding.
INFO Added finalizers to custom resource definitions.
INFO Created Trident service.
INFO Created Trident secret.
INFO Created Trident deployment.
INFO Created Trident daemonset.
INFO Waiting for Trident pod to start.
INFO Trident pod started.                          namespace=trident pod=trident-controller-679648bd45-cv2mx
INFO Waiting for Trident REST interface.
INFO Trident REST interface is up.                 version=25.06.0
INFO Trident installation succeeded.
....
----


== Überprüfen der Installation

Sie können Ihre Installation mithilfe des Pod-Erstellungsstatus überprüfen oder `tridentctl` .



=== Verwendung des Pod-Erstellungsstatus

Sie können überprüfen, ob die Trident -Installation abgeschlossen wurde, indem Sie den Status der erstellten Pods einsehen:

[listing]
----
kubectl get pods -n trident

NAME                                  READY   STATUS    RESTARTS   AGE
trident-controller-679648bd45-cv2mx   6/6     Running   0          5m29s
trident-node-linux-vgc8n              2/2     Running   0          5m29s
----

NOTE: Wenn die Installation nicht erfolgreich abgeschlossen wird oder `trident-controller-<generated id>` (`trident-csi-<generated id>` Wenn in Versionen vor 23.01 kein *Running*-Status vorhanden ist, wurde die Plattform nicht installiert.  Verwenden `-d` Zulink:../troubleshooting.html#troubleshooting-an-unsuccessful-trident-deployment-using-tridentctl["Debug-Modus aktivieren"] und das Problem beheben.



=== Verwenden `tridentctl`

Sie können verwenden `tridentctl` um die installierte Version von Trident zu überprüfen.

[listing]
----
./tridentctl -n trident version

+----------------+----------------+
| SERVER VERSION | CLIENT VERSION |
+----------------+----------------+
| 25.06.0        | 25.06.0        |
+----------------+----------------+
----


== Beispielkonfigurationen

Die folgenden Beispiele enthalten Beispielkonfigurationen für die Installation von Trident mit `tridentctl` .

.Windows-Knoten
[%collapsible]
====
Um Trident auf Windows-Knoten auszuführen:

[listing]
----
tridentctl install --windows -n trident
----
====
.Gewalttrennung
[%collapsible]
====
Weitere Informationen zum erzwungenen Abkoppeln finden Sie unterlink:..trident-get-started/kubernetes-customize-deploy.html["Anpassung der Trident -Bedieninstallation"] .

[listing]
----
tridentctl install --enable-force-detach=true -n trident
----
====
.Aktivieren Sie gleichzeitige Trident -Controller-Operationen
[%collapsible]
====
Um gleichzeitige Trident -Controller-Operationen für einen verbesserten Durchsatz zu ermöglichen, fügen Sie Folgendes hinzu: `--enable-concurrency` Option während der Installation, wie in diesem Beispiel gezeigt.


NOTE: *Technische Vorschau*: Diese Funktion ist in NetApp Trident 25.06 experimentell und unterstützt derzeit begrenzte parallele Workflows mit dem ONTAP-SAN-Treiber (iSCSI- und FCP-Protokolle).

[listing]
----
tridentctl install --enable-concurrency -n trident
----
====