---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-deploy-operator-mirror.html 
keywords: deploy, Trident, methods, operator, tridentctl, mirrored, registry, registries 
summary: Sie können den Trident -Operator manuell bereitstellen, um Trident zu installieren.  Dieser Prozess gilt für Installationen, bei denen die von Trident benötigten Container-Images in einer privaten Registry gespeichert sind. 
---
= Manuelle Aktivierung des Trident -Operators (Offline-Modus)
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können den Trident -Operator manuell bereitstellen, um Trident zu installieren.  Dieser Prozess gilt für Installationen, bei denen die von Trident benötigten Container-Images in einer privaten Registry gespeichert sind.  Wenn Sie keine private Bildregistrierung besitzen, verwenden Sie dielink:kubernetes-deploy-operator.html["Prozess für die Standardbereitstellung"] .



== Wichtige Informationen zu Trident 25.06

*Sie müssen die folgenden wichtigen Informationen über Trident unbedingt lesen.*

.<strong>Wichtige Informationen zu Trident</strong>
[%collapsible%open]
====
[]
=====
* Kubernetes 1.34 wird jetzt in Trident unterstützt. Aktualisieren Sie Trident , bevor Sie Kubernetes aktualisieren.
* Trident setzt die Verwendung von Multipathing-Konfigurationen in SAN-Umgebungen strikt durch, mit einem empfohlenen Wert von `find_multipaths: no` in der Datei multipath.conf.
+
Verwendung einer Nicht-Multipathing-Konfiguration oder Verwendung von `find_multipaths: yes` oder `find_multipaths: smart` Ein falscher Wert in der Datei multipath.conf führt zu Mount-Fehlern.  Trident hat die Verwendung von `find_multipaths: no` seit der Version vom 21.07.



=====
====


== Den Trident -Operator manuell bereitstellen und Trident installieren

Rezensionlink:../trident-get-started/kubernetes-deploy.html["Installationsübersicht"] um sicherzustellen, dass Sie die Installationsvoraussetzungen erfüllt und die richtige Installationsoption für Ihre Umgebung ausgewählt haben.

.Bevor Sie beginnen
Melden Sie sich am Linux-Host an und überprüfen Sie, ob er ein funktionierendes System verwaltet.link:requirements.html["unterstützter Kubernetes-Cluster"^] und dass Sie über die notwendigen Berechtigungen verfügen.


NOTE: Mit OpenShift verwenden Sie `oc` anstatt `kubectl` Melden Sie sich in allen folgenden Beispielen zuerst als *system:admin* an, indem Sie folgenden Befehl ausführen `oc login -u system:admin` oder `oc login -u kube-admin` .

[%collapsible%open]
====
. Überprüfen Sie Ihre Kubernetes-Version:
+
[listing]
----
kubectl version
----
. Überprüfen Sie die Cluster-Administratorrechte:
+
[listing]
----
kubectl auth can-i '*' '*' --all-namespaces
----
. Überprüfen Sie, ob Sie einen Pod starten können, der ein Image von Docker Hub verwendet, und Ihr Speichersystem über das Pod-Netzwerk erreichen können:
+
[listing]
----
kubectl run -i --tty ping --image=busybox --restart=Never --rm -- \
  ping <management IP>
----


====


=== Schritt 1: Laden Sie das Trident Installationspaket herunter

Das Trident -Installationspaket enthält alles, was Sie zum Bereitstellen des Trident -Operators und zum Installieren von Trident benötigen.  Laden Sie die neueste Version des Trident -Installationsprogramms herunter und extrahieren Sie sie vonlink:https://github.com/NetApp/trident/releases/latest["der Abschnitt „Assets“ auf GitHub"^] .

[listing]
----
wget https://github.com/NetApp/trident/releases/download/v6.0/trident-installer-25.06.0.tar.gz
tar -xf trident-installer-25.06.0.tar.gz
cd trident-installer
----


=== Schritt 2: Erstellen Sie die `TridentOrchestrator` CRD

Erstellen Sie die `TridentOrchestrator` Benutzerdefinierte Ressourcendefinition (CRD).  Sie werden ein/e erstellen `TridentOrchestrator` Benutzerdefinierte Ressourcen später.  Verwenden Sie die entsprechende CRD-YAML-Version in `deploy/crds` um die `TridentOrchestrator` CRD:

[listing]
----
kubectl create -f deploy/crds/<VERSION>.yaml
----


=== Schritt 3: Aktualisieren Sie den Registrierungsspeicherort im Operator

In `/deploy/operator.yaml` , aktualisieren `image: docker.io/netapp/trident-operator:25.06.0` um den Speicherort Ihrer Bildregistrierung widerzuspiegeln.  Deinlink:../trident-get-started/requirements.html#container-images-and-corresponding-kubernetes-versions["Trident und CSI-Bilder"] Die CSI-Images können sich in einem oder mehreren Registrys befinden, aber alle CSI-Images müssen sich im selben Registry befinden. Beispiel:

* `image: <your-registry>/trident-operator:25.06.0`wenn sich alle Ihre Bilder in einem einzigen Verzeichnis befinden.
* `image: <your-registry>/netapp/trident-operator:25.06.0`wenn sich Ihr Trident Image in einem anderen Verzeichnis befindet als Ihre CSI-Images.




=== Schritt 4: Den Trident -Operator einsetzen

Das Trident -Installationsprogramm stellt eine Bundle-Datei bereit, mit der der Operator installiert und zugehörige Objekte erstellt werden können.  Die Bundle-Datei ist eine einfache Möglichkeit, den Operator bereitzustellen und Trident mit einer Standardkonfiguration zu installieren.

* Für Cluster, auf denen Kubernetes 1.24 läuft, verwenden Sie `bundle_pre_1_25.yaml` .
* Für Cluster, auf denen Kubernetes 1.25 oder höher ausgeführt wird, verwenden Sie `bundle_post_1_25.yaml` .


.Bevor Sie beginnen
* Standardmäßig installiert das Trident -Installationsprogramm den Operator im `trident` Namespace.  Wenn die `trident` Der Namespace existiert nicht. Erstellen Sie ihn mit folgendem Befehl:
+
[listing]
----
kubectl apply -f deploy/namespace.yaml
----
* Um den Operator in einem anderen Namespace als dem bereitzustellen `trident` Namespace aktualisieren `serviceaccount.yaml` , `clusterrolebinding.yaml` Und `operator.yaml` und generieren Sie Ihre Bundle-Datei mithilfe des `kustomization.yaml` .
+
.. Erstellen Sie die `kustomization.yaml` mit dem folgenden Befehl, wobei _<bundle.yaml>_ ist `bundle_pre_1_25.yaml` oder `bundle_post_1_25.yaml` basierend auf Ihrer Kubernetes-Version.
+
[listing]
----
cp deploy/kustomization_<bundle.yaml> deploy/kustomization.yaml
----
.. Kompilieren Sie das Bundle mit dem folgenden Befehl, wobei _<bundle.yaml>_ für `bundle_pre_1_25.yaml` oder `bundle_post_1_25.yaml` basierend auf Ihrer Kubernetes-Version.
+
[listing]
----
kubectl kustomize deploy/ > deploy/<bundle.yaml>
----




.Schritte
. Ressourcen erstellen und Operator bereitstellen:
+
[listing]
----
kubectl create -f deploy/<bundle.yaml>
----
. Überprüfen Sie, ob der Operator, die Bereitstellung und die Replikatsätze erstellt wurden.
+
[listing]
----
kubectl get all -n <operator-namespace>
----



IMPORTANT: Es sollte nur *eine Instanz* des Operators in einem Kubernetes-Cluster geben.  Erstellen Sie keine Mehrfachinstallationen des Trident -Operators.



=== Schritt 5: Aktualisieren Sie den Speicherort der Bildregistrierung in der `TridentOrchestrator`

Deinlink:../trident-get-started/requirements.html#container-images-and-corresponding-kubernetes-versions["Trident und CSI-Bilder"] Die CSI-Images können sich in einem oder mehreren Registrys befinden, aber alle CSI-Images müssen sich im selben Registry befinden.  Aktualisieren `deploy/crds/tridentorchestrator_cr.yaml` um die zusätzlichen Standortangaben basierend auf Ihrer Registry-Konfiguration hinzuzufügen.

[role="tabbed-block"]
====
.Bilder in einem Register
--
[listing]
----
imageRegistry: "<your-registry>"
autosupportImage: "<your-registry>/trident-autosupport:25.06"
tridentImage: "<your-registry>/trident:25.06.0"
----
--
.Bilder in verschiedenen Registern
--
[listing]
----
imageRegistry: "<your-registry>"
autosupportImage: "<your-registry>/trident-autosupport:25.06"
tridentImage: "<your-registry>/trident:25.06.0"
----
--
====


=== Schritt 6: Erstellen Sie die `TridentOrchestrator` und installieren Sie Trident

Sie können jetzt die erstellen `TridentOrchestrator` und installieren Sie Trident.  Optional können Sie außerdemlink:kubernetes-customize-deploy.html["Passen Sie Ihre Trident -Installation individuell an."] unter Verwendung der Attribute in der `TridentOrchestrator` Spezifikation.  Das folgende Beispiel zeigt eine Installation, bei der sich Trident und CSI-Images in unterschiedlichen Registries befinden.

[listing]
----
kubectl create -f deploy/crds/tridentorchestrator_cr.yaml
tridentorchestrator.trident.netapp.io/trident created

kubectl describe torc trident

Name:        trident
Namespace:
Labels:      <none>
Annotations: <none>
API Version: trident.netapp.io/v1
Kind:        TridentOrchestrator
...
Spec:
  Autosupport Image:  <your-registry>/trident-autosupport:25.06
  Debug:              true
  Image Registry:     <your-registry>
  Namespace:          trident
  Trident Image:      <your-registry>/trident:25.06.0
Status:
  Current Installation Params:
    IPv6:                       false
    Autosupport Hostname:
    Autosupport Image:          <your-registry>/trident-autosupport:25.06
    Autosupport Proxy:
    Autosupport Serial Number:
    Debug:                      true
    Http Request Timeout:       90s
    Image Pull Secrets:
    Image Registry:       <your-registry>
    k8sTimeout:           30
    Kubelet Dir:          /var/lib/kubelet
    Log Format:           text
    Probe Port:           17546
    Silence Autosupport:  false
    Trident Image:        <your-registry>/trident:25.06.0
  Message:                Trident installed
  Namespace:              trident
  Status:                 Installed
  Version:                v25.06.0
Events:
    Type Reason Age From Message ---- ------ ---- ---- -------Normal
    Installing 74s trident-operator.netapp.io Installing Trident Normal
    Installed 67s trident-operator.netapp.io Trident installed
----


== Überprüfen der Installation

Es gibt mehrere Möglichkeiten, Ihre Installation zu überprüfen.



=== Verwenden `TridentOrchestrator` Status

Der Status von `TridentOrchestrator` Zeigt an, ob die Installation erfolgreich war und welche Version von Trident installiert wurde.  Während der Installation wird der Status von `TridentOrchestrator` Änderungen von `Installing` Zu `Installed` .  Wenn Sie die `Failed` Status und der Betreiber kann sich nicht selbst erholenlink:../troubleshooting.html["Überprüfen Sie die Protokolle."] .

[cols="2"]
|===
| Status | Beschreibung 


| Installieren | Der Bediener installiert Trident mithilfe dieses Befehls `TridentOrchestrator` CR. 


| Installiert | Trident wurde erfolgreich installiert. 


| Deinstallation | Der Betreiber deinstalliert Trident, weil
`spec.uninstall=true` . 


| Deinstalliert | Trident ist deinstalliert. 


| Fehlgeschlagen | Der Benutzer konnte Trident nicht installieren, patchen, aktualisieren oder deinstallieren; der Benutzer wird automatisch versuchen, diesen Zustand wiederherzustellen.  Wenn dieser Zustand anhält, ist eine Fehlerbehebung erforderlich. 


| Aktualisierung | Der Betreiber aktualisiert eine bestehende Installation. 


| Fehler | Der `TridentOrchestrator` wird nicht verwendet.  Ein anderes Exemplar existiert bereits. 
|===


=== Verwendung des Pod-Erstellungsstatus

Sie können überprüfen, ob die Trident -Installation abgeschlossen wurde, indem Sie den Status der erstellten Pods einsehen:

[listing]
----
kubectl get pods -n trident

NAME                                       READY   STATUS    RESTARTS   AGE
trident-controller-7d466bf5c7-v4cpw        6/6     Running   0           1m
trident-node-linux-mr6zc                   2/2     Running   0           1m
trident-node-linux-xrp7w                   2/2     Running   0           1m
trident-node-linux-zh2jt                   2/2     Running   0           1m
trident-operator-766f7b8658-ldzsv          1/1     Running   0           3m
----


=== Verwenden `tridentctl`

Sie können verwenden `tridentctl` um die installierte Version von Trident zu überprüfen.

[listing]
----
./tridentctl -n trident version

+----------------+----------------+
| SERVER VERSION | CLIENT VERSION |
+----------------+----------------+
| 25.06.0        | 25.06.0        |
+----------------+----------------+
----