= Datenübertragungs-Timeout-Anmerkung
:allow-uri-read: 




== Datenübertragungs-Timeout-Anmerkung

Während Sicherungs- und Wiederherstellungsvorgängen können Sie die Annotation verwenden. `protect.trident.netapp.io/data-mover-timeout-sec` um das Timeout für Datenverschiebungsvorgänge zu konfigurieren.  Diese Anmerkung legt die maximale Wartezeit in Sekunden fest, die ein Datenverschiebungs-Tool auf den Abschluss einer bestimmten Operation warten soll, bevor ein Timeout auftritt.  Es ist besonders nützlich in Situationen, in denen Netzwerkprobleme oder andere Faktoren den Datentransfervorgang behindern könnten.  Es hilft dabei, blockierte Vorgänge zu erkennen und zu beheben, anstatt ein allgemeines Timeout für den gesamten Prozess festzulegen.  Wenn beispielsweise aufgrund von Netzwerkproblemen keine Fortschritte bei der Wiederherstellung der Datenträgerdaten erzielt werden können, wird der Vorgang nach Ablauf der angegebenen Zeit abgebrochen.

Sie können diese Annotation in Ihrer YAML-Datei wie unten gezeigt verwenden:

[source, yaml]
----
---
apiVersion: protect.trident.netapp.io/v1
kind: BackupRestore
metadata:
  name: bkp-restore-kopia
  namespace: trident-protect
  annotations: # Optional annotations to configure data movement timeout
    protect.trident.netapp.io/data-mover-timeout-sec: "2"
spec:
  appVaultRef: appvault-name
  appArchivePath: my-backup-path
  namespaceMapping: [{"source": "my-source-namespace", "destination": "my-destination-namespace"}]
  storageClassMapping:
    destination: "${destinationStorageClass}"
    source: "${sourceStorageClass}"
----
In diesem Beispiel schlägt die Annotation fehl. `BackupRestore` Vorgang wird abgebrochen, wenn innerhalb von 2 Sekunden kein Fortschritt bei der Wiederherstellung erzielt wird.


NOTE: Ist der Wert der Annotation kleiner oder gleich 0, schlägt die Operation sofort fehl.
