= 
:allow-uri-read: 


Trident Protect 24.10 und 24.10.1 sowie neuere Versionen verhalten sich unterschiedlich, wenn Sie Anwendungen schützen, die auf KubeVirt VMs ausgeführt werden.  Bei beiden Versionen können Sie das Einfrieren und Auftauen des Dateisystems während Datensicherungsvorgängen aktivieren oder deaktivieren.


NOTE: Während der Wiederherstellungsvorgänge `VirtualMachineSnapshots` Für eine virtuelle Maschine (VM) erstellte Daten werden nicht wiederhergestellt.

.Trident 24.10
Trident Protect 24.10 gewährleistet nicht automatisch einen konsistenten Zustand der KubeVirt VM-Dateisysteme während Datensicherungsvorgängen.  Wenn Sie Ihre KubeVirt VM-Daten mit Trident protect 24.10 schützen möchten, müssen Sie die Freeze/Unfreeze-Funktionalität für die Dateisysteme vor dem Datensicherungsvorgang manuell aktivieren.  Dadurch wird sichergestellt, dass sich die Dateisysteme in einem konsistenten Zustand befinden.

Sie können Trident Protect 24.10 so konfigurieren, dass das Einfrieren und Auftauen des VM-Dateisystems während Datensicherungsvorgängen verwaltet wird, indemlink:https://docs.openshift.com/container-platform/4.16/virt/install/installing-virt.html["Virtualisierung konfigurieren"^] und anschließend mit folgendem Befehl:

[source, console]
----
kubectl set env deployment/trident-protect-controller-manager NEPTUNE_VM_FREEZE=true -n trident-protect
----
.Trident Protect 24.10.1 und neuer
Ab Trident protect 24.10.1 friert Trident protect KubeVirt-Dateisysteme während Datensicherungsvorgängen automatisch ein und wieder auf.  Optional können Sie dieses automatische Verhalten mit folgendem Befehl deaktivieren:

[source, console]
----
kubectl set env deployment/trident-protect-controller-manager NEPTUNE_VM_FREEZE=false -n trident-protect
----