---
sidebar: sidebar 
permalink: trident-get-started/intro.html 
keywords: product overview, Trident, fsx, element, google cloud, cvs, architecture, node pod, controller pod, pods, csi, sidecar 
summary: 'Trident ist ein vollständig unterstütztes Open-Source-Projekt, das von NetApp betreut wird.  Es wurde entwickelt, um Ihnen dabei zu helfen, die Persistenzanforderungen Ihrer containerisierten Anwendung mithilfe von branchenüblichen Schnittstellen wie dem Container Storage Interface (CSI) zu erfüllen.' 
---
= Erfahren Sie mehr über Trident
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Trident ist ein vollständig unterstütztes Open-Source-Projekt, das von NetApp betreut wird.  Es wurde entwickelt, um Ihnen dabei zu helfen, die Persistenzanforderungen Ihrer containerisierten Anwendung mithilfe von branchenüblichen Schnittstellen wie dem Container Storage Interface (CSI) zu erfüllen.



== Was ist Trident?

NetApp Trident ermöglicht die Nutzung und Verwaltung von Speicherressourcen über alle gängigen NetApp Speicherplattformen hinweg, sowohl in der Public Cloud als auch On-Premises, einschließlich On-Premises ONTAP Cluster (AFF, FAS und ASA), ONTAP Select, Cloud Volumes ONTAP, Element-Software (NetApp HCI, SolidFire), Azure NetApp Files, Amazon FSx for NetApp ONTAP und Cloud Volumes Service auf Google Cloud.

Trident ist ein Container Storage Interface (CSI)-konformer dynamischer Speicherorchestrator, der sich nativ integrieren lässt mitlink:https://kubernetes.io/["Kubernetes"^] .  Trident läuft als einzelner Controller-Pod plus ein Node-Pod auf jedem Worker-Knoten im Cluster. Siehe link:../trident-get-started/architecture.html["Trident -Architektur"] für Details.

Trident bietet außerdem eine direkte Integration mit dem Docker-Ökosystem für NetApp Speicherplattformen.  Das NetApp Docker Volume Plugin (nDVP) unterstützt die Bereitstellung und Verwaltung von Speicherressourcen von der Speicherplattform zu Docker-Hosts. Siehe link:../trident-docker/deploy-docker.html["Trident für Docker bereitstellen"] für Details.


NOTE: Wenn Sie Kubernetes zum ersten Mal verwenden, sollten Sie sich mit den folgenden Grundlagen vertraut machen:link:https://kubernetes.io/docs/home/["Kubernetes-Konzepte und -Werkzeuge"^] .



== Kubernetes-Integration mit NetApp -Produkten

Das NetApp Portfolio an Speicherprodukten integriert sich in viele Aspekte eines Kubernetes-Clusters und bietet fortschrittliche Datenverwaltungsfunktionen, die die Funktionalität, Leistungsfähigkeit, Performance und Verfügbarkeit der Kubernetes-Bereitstellung verbessern.

.Amazon FSx for NetApp ONTAP
[%collapsible]
====
link:https://www.netapp.com/aws/fsx-ontap/["Amazon FSx for NetApp ONTAP"^]ist ein vollständig verwalteter AWS-Service, mit dem Sie Dateisysteme starten und ausführen können, die auf dem Speicherbetriebssystem NetApp ONTAP basieren.

====
.Azure NetApp Files
[%collapsible]
====
https://www.netapp.com/azure/azure-netapp-files/["Azure NetApp Files"^]ist ein Azure-Dateifreigabedienst der Enterprise-Klasse, der von NetApp bereitgestellt wird.  Sie können Ihre anspruchsvollsten dateibasierten Workloads nativ in Azure ausführen und dabei die Leistung und das umfassende Datenmanagement nutzen, die Sie von NetApp erwarten.

====
.Cloud Volumes ONTAP
[%collapsible]
====
link:https://www.netapp.com/cloud-services/cloud-volumes-ontap/["Cloud Volumes ONTAP"^]ist ein rein softwarebasiertes Speichersystem, auf dem die Datenverwaltungssoftware ONTAP in der Cloud ausgeführt wird.

====
.Google Cloud NetApp Volumes
[%collapsible]
====
link:https://bluexp.netapp.com/google-cloud-netapp-volumes?utm_source=GitHub&utm_campaign=Trident["Google Cloud NetApp Volumes"^]ist ein vollständig verwalteter Dateispeicherdienst in Google Cloud, der hochleistungsfähigen Dateispeicher auf Unternehmensebene bietet.

====
.Element Software
[%collapsible]
====
https://www.netapp.com/data-management/element-software/["Element"^]ermöglicht es dem Speicheradministrator, Arbeitslasten zu konsolidieren, indem die Leistung gewährleistet und ein vereinfachter und optimierter Speicherbedarf ermöglicht wird.

====
.NetApp HCI
[%collapsible]
====
link:https://docs.netapp.com/us-en/hci/docs/concept_hci_product_overview.html["NetApp HCI"^]vereinfacht die Verwaltung und Skalierung des Rechenzentrums durch die Automatisierung von Routineaufgaben und ermöglicht es Infrastrukturadministratoren, sich auf wichtigere Funktionen zu konzentrieren.

Trident kann Speichergeräte für containerisierte Anwendungen direkt auf der zugrunde liegenden NetApp HCI -Speicherplattform bereitstellen und verwalten.

====
.NetApp ONTAP
[%collapsible]
====
link:https://docs.netapp.com/us-en/ontap/index.html["NetApp ONTAP"^]ist das Multiprotokoll-Betriebssystem von NetApp für einheitliche Speichersysteme, das fortschrittliche Datenverwaltungsfunktionen für jede Anwendung bietet.

ONTAP Systeme verfügen über All-Flash-, Hybrid- oder All-HDD-Konfigurationen und bieten viele verschiedene Bereitstellungsmodelle: lokale FAS, AFA- und ASA Cluster, ONTAP Select und Cloud Volumes ONTAP.  Trident unterstützt diese ONTAP Bereitstellungsmodelle.

====