---
sidebar: sidebar 
permalink: trident-protect/trident-protect-migrate-apps.html 
keywords: trident, protect, migrate, storage, restore, backup 
summary: Sie können Ihre Sicherungs- oder Snapshot-Daten in einem anderen Cluster oder einer anderen Speicherklasse wiederherstellen. 
---
= Anwendungen mit Trident Protect migrieren
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sie können Ihre Anwendungen zwischen Clustern oder in verschiedene Speicherklassen migrieren, indem Sie Sicherungsdaten wiederherstellen.


NOTE: Bei der Migration einer Anwendung werden alle für die Anwendung konfigurierten Ausführungs-Hooks mit der Anwendung migriert.  Wenn ein Hook für die Nachbearbeitung der Wiederherstellung vorhanden ist, wird dieser automatisch im Rahmen des Wiederherstellungsvorgangs ausgeführt.



== Sicherungs- und Wiederherstellungsvorgänge

Um Sicherungs- und Wiederherstellungsvorgänge für die folgenden Szenarien durchzuführen, können Sie bestimmte Sicherungs- und Wiederherstellungsaufgaben automatisieren.



=== Klonen auf denselben Cluster

Um eine Anwendung auf denselben Cluster zu klonen, erstellen Sie einen Snapshot oder eine Sicherung und stellen Sie die Daten auf demselben Cluster wieder her.

.Schritte
. Führen Sie einen der folgenden Schritte aus:
+
.. link:trident-protect-protect-apps.html#create-an-on-demand-snapshot["Erstellen eines Snapshots"].
.. link:trident-protect-protect-apps.html#create-an-on-demand-backup["Erstellen Sie ein Backup"].


. Führen Sie auf demselben Cluster einen der folgenden Schritte aus, je nachdem, ob Sie einen Snapshot oder eine Sicherung erstellt haben:
+
.. link:trident-protect-restore-apps.html#restore-from-a-snapshot-to-a-different-namespace["Stellen Sie Ihre Daten aus dem Snapshot wieder her."].
.. link:trident-protect-restore-apps.html#restore-from-a-backup-to-a-different-namespace["Stellen Sie Ihre Daten aus der Sicherung wieder her."].






=== Klonen auf anderen Cluster

Um eine Anwendung auf einen anderen Cluster zu klonen (clusterübergreifendes Klonen), erstellen Sie eine Sicherung auf dem Quellcluster und stellen Sie diese Sicherung anschließend auf dem anderen Cluster wieder her. Stellen Sie sicher, dass Trident Protect auf dem Zielcluster installiert ist.


NOTE: Sie können eine Anwendung zwischen verschiedenen Clustern replizieren, indem Sielink:trident-protect-use-snapmirror-replication.html["SnapMirror -Replikation"] .

.Schritte
. link:trident-protect-protect-apps.html#create-an-on-demand-backup["Erstellen Sie ein Backup"].
. Stellen Sie sicher, dass der AppVault CR für den Objektspeicher-Bucket, der das Backup enthält, auf dem Zielcluster konfiguriert wurde.
. Auf dem Zielcluster,link:trident-protect-restore-apps.html#restore-from-a-backup-to-a-different-namespace["Stellen Sie Ihre Daten aus der Sicherung wieder her."] .




== Anwendungen von einer Speicherklasse in eine andere Speicherklasse migrieren

Sie können Anwendungen von einer Speicherklasse in eine andere Speicherklasse migrieren, indem Sie eine Sicherung in der Zielspeicherklasse wiederherstellen.

Zum Beispiel (ohne die Geheimnisse aus dem Wiederherstellungs-CR):

[source, yaml]
----
apiVersion: protect.trident.netapp.io/v1
kind: SnapshotRestore
metadata:
  name: "${snapshotRestoreCRName}"
spec:
  appArchivePath: "${snapshotArchivePath}"
  appVaultRef: "${appVaultCRName}"
  namespaceMapping:
    - destination: "${destinationNamespace}"
      source: "${sourceNamespace}"
  storageClassMapping:
    - destination: "${destinationStorageClass}"
      source: "${sourceStorageClass}"
  resourceFilter:
    resourceMatchers:
      kind: Secret
      version: v1
    resourceSelectionCriteria: exclude
----
[role="tabbed-block"]
====
.Stellen Sie den Snapshot mithilfe einer CR wieder her.
--
.Schritte
. Erstellen Sie die benutzerdefinierte Ressourcendatei (CR-Datei) und benennen Sie sie. `trident-protect-snapshot-restore-cr.yaml` .
. Konfigurieren Sie in der von Ihnen erstellten Datei die folgenden Attribute:
+
** *metadata.name*: (_Erforderlich_) Der Name dieser benutzerdefinierten Ressource; wählen Sie einen eindeutigen und aussagekräftigen Namen für Ihre Umgebung.
** *spec.appArchivePath*: Der Pfad innerhalb von AppVault, in dem die Snapshot-Inhalte gespeichert sind.  Sie können folgenden Befehl verwenden, um diesen Pfad zu finden:
+
[source, console]
----
kubectl get snapshots <my-snapshot-name> -n trident-protect -o jsonpath='{.status.appArchivePath}'
----
** *spec.appVaultRef*: (_Erforderlich_) Der Name des AppVaults, in dem die Snapshot-Inhalte gespeichert sind.
** *spec.namespaceMapping*: Die Zuordnung des Quell-Namespace der Wiederherstellungsoperation zum Ziel-Namespace.  Ersetzen `my-source-namespace` Und `my-destination-namespace` mit Informationen aus Ihrer Umgebung.
+
[source, yaml]
----
---
apiVersion: protect.trident.netapp.io/v1
kind: SnapshotRestore
metadata:
  name: my-cr-name
  namespace: trident-protect
spec:
  appArchivePath: my-snapshot-path
  appVaultRef: appvault-name
  namespaceMapping: [{"source": "my-source-namespace", "destination": "my-destination-namespace"}]
----


. Optional können Sie, falls Sie nur bestimmte Ressourcen der Anwendung für die Wiederherstellung auswählen möchten, Filter hinzufügen, die Ressourcen mit bestimmten Bezeichnungen ein- oder ausschließen:
+
** *resourceFilter.resourceSelectionCriteria*: (Für die Filterung erforderlich) Verwenden Sie `include or exclude` Eine in resourceMatchers definierte Ressource ein- oder ausschließen.  Fügen Sie die folgenden resourceMatchers-Parameter hinzu, um die ein- oder auszuschließenden Ressourcen zu definieren:
+
*** *resourceFilter.resourceMatchers*: Ein Array von resourceMatcher-Objekten.  Wenn Sie mehrere Elemente in diesem Array definieren, werden diese per OR-Verknüpfung abgeglichen, und die Felder innerhalb jedes Elements (Gruppe, Art, Version) werden per AND-Verknüpfung abgeglichen.
+
**** *resourceMatchers[].group*: (_Optional_) Gruppe der zu filternden Ressourcen.
**** *resourceMatchers[].kind*: (_Optional_) Art der zu filternden Ressource.
**** *resourceMatchers[].version*: (_Optional_) Version der zu filternden Ressource.
**** *resourceMatchers[].names*: (_Optional_) Namen im Kubernetes metadata.name Feld der zu filternden Ressource.
**** *resourceMatchers[].namespaces*: (_Optional_) Namespaces im Kubernetes metadata.name-Feld der zu filternden Ressource.
**** *resourceMatchers[].labelSelectors*: (_Optional_) Label-Selektorzeichenfolge im Kubernetes-Metadatenfeld „name“ der Ressource, wie in der Dokumentation definiert. https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors["Kubernetes-Dokumentation"^] .  Zum Beispiel: `"trident.netapp.io/os=linux"` .
+
Beispiel:

+
[source, yaml]
----
spec:
  resourceFilter:
    resourceSelectionCriteria: "include"
    resourceMatchers:
      - group: my-resource-group-1
        kind: my-resource-kind-1
        version: my-resource-version-1
        names: ["my-resource-names"]
        namespaces: ["my-resource-namespaces"]
        labelSelectors: ["trident.netapp.io/os=linux"]
      - group: my-resource-group-2
        kind: my-resource-kind-2
        version: my-resource-version-2
        names: ["my-resource-names"]
        namespaces: ["my-resource-namespaces"]
        labelSelectors: ["trident.netapp.io/os=linux"]
----






. Nachdem Sie die `trident-protect-snapshot-restore-cr.yaml` Datei mit den korrekten Werten, CR anwenden:
+
[source, console]
----
kubectl apply -f trident-protect-snapshot-restore-cr.yaml
----


--
.Stellen Sie den Snapshot mithilfe der Befehlszeile wieder her.
--
.Schritte
. Stellen Sie den Snapshot in einem anderen Namespace wieder her und ersetzen Sie die Werte in Klammern durch Informationen aus Ihrer Umgebung.
+
** Der `snapshot` Das Argument verwendet einen Namespace und einen Snapshot-Namen im folgenden Format: `<namespace>/<name>` .
** Der `namespace-mapping` Das Argument verwendet durch Doppelpunkte getrennte Namensräume, um Quell-Namensräume den korrekten Ziel-Namensräumen im folgenden Format zuzuordnen: `source1:dest1,source2:dest2` .
+
Beispiel:

+
[source, console]
----
tridentctl-protect create snapshotrestore <my_restore_name> --snapshot <namespace/snapshot_to_restore> --namespace-mapping <source_to_destination_namespace_mapping>
----




--
====