---
sidebar: sidebar 
permalink: trident-protect/trident-protect-customize-installation.html 
keywords: customize, trident protect, resource limits, security context constraints, SCC, NetApp AutoSupport, proxy connection, helm, helm chart, helm upgrade 
summary: Passen Sie die Standardeinstellungen von Trident Protect an Ihre spezifischen Bedürfnisse an. 
---
= Trident Protect-Installation anpassen
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Standardkonfiguration von Trident Protect an die spezifischen Anforderungen Ihrer Umgebung anpassen.



== Legen Sie die Ressourcenbeschränkungen für Trident Protect-Container fest.

Sie können nach der Installation von Trident Protect eine Konfigurationsdatei verwenden, um Ressourcenlimits für Trident Protect-Container festzulegen. Durch das Festlegen von Ressourcenlimits können Sie steuern, wie viele der Clusterressourcen von Trident Protect-Operationen verbraucht werden.

.Schritte
. Erstellen Sie eine Datei mit dem Namen `resourceLimits.yaml` .
. Füllen Sie die Datei mit Ressourcenlimitierungsoptionen für Trident Protect-Container entsprechend den Anforderungen Ihrer Umgebung.
+
Die folgende Beispielkonfigurationsdatei zeigt die verfügbaren Einstellungen und enthält die Standardwerte für jedes Ressourcenlimit:

+
[source, yaml]
----
---
jobResources:
  defaults:
    limits:
      cpu: 8000m
      memory: 10000Mi
      ephemeralStorage: ""
    requests:
      cpu: 100m
      memory: 100Mi
      ephemeralStorage: ""
  resticVolumeBackup:
    limits:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
    requests:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
  resticVolumeRestore:
    limits:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
    requests:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
  kopiaVolumeBackup:
    limits:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
    requests:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
  kopiaVolumeRestore:
    limits:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
    requests:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
----
. Wenden Sie die Werte aus dem `resourceLimits.yaml` Datei:
+
[source, console]
----
helm upgrade trident-protect -n trident-protect netapp-trident-protect/trident-protect -f resourceLimits.yaml --reuse-values
----




== Sicherheitskontextbeschränkungen anpassen

Sie können eine Konfigurationsdatei verwenden, um die OpenShift-Sicherheitskontextbeschränkungen (SCCs) für Trident Protect-Container nach der Installation von Trident Protect zu ändern. Diese Einschränkungen definieren Sicherheitsbeschränkungen für Pods in einem Red Hat OpenShift-Cluster.

.Schritte
. Erstellen Sie eine Datei mit dem Namen `sccconfig.yaml` .
. Fügen Sie die SCC-Option zur Datei hinzu und passen Sie die Parameter an die Bedürfnisse Ihrer Umgebung an.
+
Das folgende Beispiel zeigt die Standardwerte der Parameter für die SCC-Option:

+
[source, yaml]
----
scc:
  create: true
  name: trident-protect-job
  priority: 1
----
+
Diese Tabelle beschreibt die Parameter für die SCC-Option:

+
|===
| Parameter | Beschreibung | Standard 


| erstellen | Ermittelt, ob eine SCC-Ressource erstellt werden kann.  Eine SCC-Ressource wird nur dann erstellt, wenn `scc.create` ist eingestellt auf `true` und der Helm-Installationsprozess erkennt eine OpenShift-Umgebung.  Wenn der Betrieb nicht auf OpenShift erfolgt, oder wenn `scc.create` ist eingestellt auf `false` Es wird keine SCC-Ressource erstellt. | true 


| Name | Gibt den Namen des SCC an. | trident-protect-job 


| Priorität | Definiert die Priorität des SCC.  SCCs mit höheren Prioritätswerten werden vor solchen mit niedrigeren Werten bewertet. | 1 
|===
. Wenden Sie die Werte aus dem `sccconfig.yaml` Datei:
+
[source, console]
----
helm upgrade trident-protect netapp-trident-protect/trident-protect -f sccconfig.yaml --reuse-values
----
+
Dadurch werden die Standardwerte durch die in der `sccconfig.yaml` Datei.





== Konfigurieren Sie zusätzliche Trident Protect Helm-Chart-Einstellungen

Sie können die AutoSupport Einstellungen und die Namespace-Filterung an Ihre spezifischen Anforderungen anpassen. In der folgenden Tabelle werden die verfügbaren Konfigurationsparameter beschrieben:

|===
| Parameter | Typ | Beschreibung 


| autoSupport.proxy | Schnur | Konfiguriert eine Proxy-URL für NetApp AutoSupport Verbindungen. Verwenden Sie dies, um Support-Bundle-Uploads über einen Proxyserver zu leiten. Beispiel: `http://my.proxy.url` . 


| autoSupport.unsicher | boolescher Wert | Überspringt die TLS-Verifizierung für AutoSupport Proxy-Verbindungen, wenn diese Option aktiviert ist. `true` . Nur für unsichere Proxy-Verbindungen verwenden.  (Standard: `false` ) 


| autoSupport.enabled | boolescher Wert | Aktiviert oder deaktiviert tägliche Trident Protect AutoSupport Bundle-Uploads. Wenn eingestellt auf `false` Tägliche Uploads sind deaktiviert, Support-Bundles können aber weiterhin manuell generiert werden. (Standard: `true` ) 


| restoreSkipNamespaceAnnotations | Schnur | Durch Kommas getrennte Liste von Namespace-Anmerkungen, die von Sicherungs- und Wiederherstellungsvorgängen ausgeschlossen werden sollen. Ermöglicht Ihnen, Namespaces basierend auf Anmerkungen zu filtern. 


| restoreSkipNamespaceLabels | Schnur | Durch Kommas getrennte Liste von Namespace-Bezeichnungen, die von Sicherungs- und Wiederherstellungsvorgängen ausgeschlossen werden sollen. Ermöglicht Ihnen, Namespaces basierend auf Labels zu filtern. 
|===
Sie können diese Optionen entweder mithilfe einer YAML-Konfigurationsdatei oder mithilfe von Befehlszeilenflags konfigurieren:

[role="tabbed-block"]
====
.YAML-Datei verwenden
--
.Schritte
. Erstellen Sie eine Konfigurationsdatei und benennen Sie sie. `values.yaml` .
. Fügen Sie in der von Ihnen erstellten Datei die Konfigurationsoptionen hinzu, die Sie anpassen möchten.
+
[source, console]
----
autoSupport:
  enabled: false
  proxy: http://my.proxy.url
  insecure: true
restoreSkipNamespaceAnnotations: "annotation1,annotation2"
restoreSkipNamespaceLabels: "label1,label2"
----
. Nachdem Sie die `values.yaml` Datei mit den korrekten Werten, Konfigurationsdatei anwenden:
+
[source, console]
----
helm upgrade trident-protect -n trident-protect netapp-trident-protect/trident-protect -f values.yaml --reuse-values
----


--
.CLI-Flag verwenden
--
.Schritte
. Verwenden Sie den folgenden Befehl mit dem `--set` Flagge zur Angabe einzelner Parameter:
+
[source, console]
----
helm upgrade trident-protect -n trident-protect netapp-trident-protect/trident-protect \
  --set autoSupport.enabled=false \
  --set autoSupport.proxy=http://my.proxy.url \
  --set restoreSkipNamespaceAnnotations="annotation1,annotation2" \
  --set restoreSkipNamespaceLabels="label1,label2" \
  --reuse-values
----


--
====


== Trident Protect-Pods auf bestimmte Knoten beschränken

Mithilfe der Kubernetes-Knotenauswahlbeschränkung nodeSelector können Sie anhand der Knotenbezeichnungen steuern, welche Ihrer Knoten für die Ausführung von Trident Protect-Pods geeignet sind. Standardmäßig ist Trident Protect auf Knoten beschränkt, auf denen Linux ausgeführt wird. Sie können diese Einschränkungen je nach Ihren Bedürfnissen weiter anpassen.

.Schritte
. Erstellen Sie eine Datei mit dem Namen `nodeSelectorConfig.yaml` .
. Fügen Sie die Option nodeSelector zur Datei hinzu und modifizieren Sie die Datei, um Knotenbezeichnungen hinzuzufügen oder zu ändern und diese entsprechend den Anforderungen Ihrer Umgebung einzuschränken.  Die folgende Datei enthält beispielsweise die Standardbeschränkung des Betriebssystems, zielt aber auch auf eine bestimmte Region und einen bestimmten Anwendungsnamen ab:
+
[source, yaml]
----
nodeSelector:
  kubernetes.io/os: linux
  region: us-west
  app.kubernetes.io/name: mysql
----
. Wenden Sie die Werte aus dem `nodeSelectorConfig.yaml` Datei:
+
[source, console]
----
helm upgrade trident-protect -n trident-protect netapp-trident-protect/trident-protect -f nodeSelectorConfig.yaml --reuse-values
----
+
Dadurch werden die Standardbeschränkungen durch die von Ihnen angegebenen Beschränkungen ersetzt. `nodeSelectorConfig.yaml` Datei.


