---
sidebar: sidebar 
permalink: trident-protect/trident-protect-generate-support-bundle.html 
keywords: trident, protect, bundle, support, netapp, custom, resource, file 
summary: 'Trident Protect ermöglicht es Administratoren, Pakete zu generieren, die für den NetApp -Support nützliche Informationen enthalten, darunter Protokolle, Metriken und Topologieinformationen über die verwalteten Cluster und Anwendungen. Wenn Sie mit dem Internet verbunden sind, können Sie Support-Bundles mithilfe einer benutzerdefinierten Ressourcendatei (CR-Datei) auf die NetApp Support Site (NSS) hochladen.' 
---
= Generieren Sie ein Trident Protect-Supportpaket
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Trident Protect ermöglicht es Administratoren, Pakete zu generieren, die für den NetApp -Support nützliche Informationen enthalten, darunter Protokolle, Metriken und Topologieinformationen über die verwalteten Cluster und Anwendungen. Wenn Sie mit dem Internet verbunden sind, können Sie Support-Pakete mithilfe einer benutzerdefinierten Ressourcendatei (CR) auf die NetApp Support Site (NSS) hochladen.

[role="tabbed-block"]
====
.Erstellen Sie ein Support-Bundle mithilfe eines CR
--
.Schritte
. Erstellen Sie die benutzerdefinierte Ressourcendatei (CR-Datei) und benennen Sie sie (zum Beispiel). `trident-protect-support-bundle.yaml` ).
. Konfigurieren Sie die folgenden Attribute:
+
** *metadata.name*: (_Erforderlich_) Der Name dieser benutzerdefinierten Ressource; wählen Sie einen eindeutigen und aussagekräftigen Namen für Ihre Umgebung.
** *spec.triggerType*: (_Erforderlich_) Legt fest, ob das Support-Bundle sofort oder geplant generiert wird.  Die geplante Bündelgenerierung erfolgt um 0:00 Uhr UTC.  Mögliche Werte:
+
*** Geplant
*** Handbuch


** *spec.uploadEnabled*: (_Optional_) Steuert, ob das Support-Bundle nach seiner Generierung auf die NetApp Support-Website hochgeladen werden soll.  Falls nicht anders angegeben, wird standardmäßig der Wert verwendet. `false` .  Mögliche Werte:
+
*** true
*** falsch (Standardeinstellung)


** *spec.dataWindowStart*: (_Optional_) Eine Datumszeichenfolge im RFC 3339-Format, die Datum und Uhrzeit angibt, zu der das Fenster der im Support-Bundle enthaltenen Daten beginnen soll.  Falls nicht anders angegeben, wird standardmäßig der Wert von vor 24 Stunden verwendet.  Das früheste Datum, das Sie angeben können, liegt 7 Tage zurück.
+
Beispiel-YAML:

+
[source, yaml]
----
---
apiVersion: protect.trident.netapp.io/v1
kind: AutoSupportBundle
metadata:
  name: trident-protect-support-bundle
spec:
  triggerType: Manual
  uploadEnabled: true
  dataWindowStart: 2024-05-05T12:30:00Z
----


. Nachdem Sie die `trident-protect-support-bundle.yaml` Datei mit den korrekten Werten, CR anwenden:
+
[source, console]
----
kubectl apply -f trident-protect-support-bundle.yaml -n trident-protect
----


--
.Erstellen Sie ein Support-Bundle mithilfe der CLI.
--
.Schritte
. Erstellen Sie das Support-Bundle und ersetzen Sie die Werte in Klammern durch Informationen aus Ihrer Umgebung.  Der `trigger-type` bestimmt, ob das Paket sofort erstellt wird oder ob die Erstellungszeit durch den Zeitplan vorgegeben ist, und kann sein `Manual` oder `Scheduled` .  Die Standardeinstellung ist `Manual` .
+
Beispiel:

+
[source, console]
----
tridentctl-protect create autosupportbundle <my-bundle-name> --trigger-type <trigger-type> -n trident-protect
----


--
====


== Überwachen und Abrufen des Support-Pakets

Nachdem Sie mit einer der beiden Methoden ein Support-Paket erstellt haben, können Sie den Generierungsfortschritt überwachen und es auf Ihr lokales System abrufen.

.Schritte
. Warten Sie auf die `status.generationState` erreichen `Completed` Zustand. Sie können den Generierungsfortschritt mit dem folgenden Befehl überwachen:
+
[source, console]
----
kubectl get autosupportbundle trident-protect-support-bundle -n trident-protect
----
. Rufen Sie das Support-Paket auf Ihr lokales System ab. Holen Sie sich den Kopierbefehl aus dem vollständigen AutoSupport Paket:
+
[source, console]
----
kubectl describe autosupportbundle trident-protect-support-bundle -n trident-protect
----
+
Finden Sie die `kubectl cp` Führen Sie den Befehl aus der Ausgabe aus und ersetzen Sie dabei das Zielargument durch Ihr bevorzugtes lokales Verzeichnis.


